### ISSUE TITLE
Need a good way to alert users about why they can't use certain functionality (eg. bc of permissions)

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#1912]
## What went wrong? 😲
In latest `v1.1.15` apk, the `Confirm sent` button is disabled and thus the internal order can't be send anymore! 
Let know if I'm missing any new updates/changes in the flow! (since it was working well in `v1.1.14`) 🤷

## Expected behaviour 🤔
The `sent` button should not be disabled

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Get latest v1.1.15 apk
2. Create a new internal order and add some lines
3. See error: the `Confirm sent` button is disabled
![Screenshot_20230614_174101_openmsupply-client](https://github.com/openmsupply/open-msupply/assets/59193490/ecdc627f-0b36-4ba7-a0f4-eacd3b447c8f)

## Your environment 🌱

 - Version: v1.1.15 apk
 - Platform:
   - android (tablet)
   - server (windows)
 
 ## Solution:
 
"Anisha says: Button enabled and toast"

**Comment by DhanyaHerath** [comment]
@roxy-dao @mark-prins do we have a preferred pattern for things that are prevented because of permission?
Two possible options are: disable the button but with a tooltip explaining why, or keep enabled and have an alert explaining why. 

I think adding at least a tooltip could be helpful here.

**Comment by mark-prins** [comment]
Already has a tooltip 😉 

I don't like the alert on an enabled button, it means I have to click to dismiss the alert. The disabled button is a good visual cue that it isn't allowed. That's personal preference though I guess.

**Comment by roxy-dao** [comment]
🤔 I noticed people don't actually use the tooltips at all....

**Comment by mark-prins** [comment]
So..? Do you think an alert would be more effective?

What about a toast? that'd be a compromise - the button is still enabled, an alert shows, and I don't have to click to get rid of the alert

The tooltip isn't very informative, now that I check it 😄 
![Screenshot 2023-06-15 at 3 11 42 PM](https://github.com/openmsupply/open-msupply/assets/9192912/aaa19394-8b23-4427-9046-6cc9c079228a)

**Comment by DhanyaHerath** [comment]
Hahha yeah I was trying to find definitive articles telling me what was the best way. I started out neutral between "disabled and tooltip" and "enabled and alert" and then I started leaning towards enabled: 
https://uxpsychology.substack.com/p/hidden-vs-disabled-states
https://axesslab.com/disabled-buttons-suck/

I'd (1) agree with Roxy that lots of people don't hover (not everything has a tooltip), (2) want to suggest we ask @anisha-msupply when she gets back (even though I now feel very strongly about my new opinion), (3) should have this consistent across omSupply and HSH

**Comment by mark-prins** [comment]
One more link: https://uxpsychology.substack.com/p/hidden-vs-disabled-states
I still find the idea of an enabled button that just alerts to tell me "you are not allowed to do this" a bit weird - happy to run with it and see.
Another option is to show a message in place of the button or different text on the button. 
I'd still go with the click+toast option as my pick if we do have to change from disabled

**Comment by DhanyaHerath** [comment]
I like the click + toast option - can that work even if the button is disabled?

**Comment by roxy-dao** [comment]
The button would not be disabled for click + toast option 🤔 ... though the other disabled buttons would need to be refactored for consistency? 

Click + toast sounds good to me.

**Comment by DhanyaHerath** [comment]
Let's leave this for when @anisha-msupply is back, and then have the decision communicated across all our products - might be good to have a guideline in Storygraph.

**Comment by andreievg** [comment]
Also disabled with a question mark that is clickable

**Comment by DhanyaHerath** [comment]
Anisha says: Button enabled and toast

**Comment by DhanyaHerath** [comment]
TODO: Document where needs to be updated to match this behaviour

**Comment by fergie-nz** [comment]
> Anisha says: Button enabled and toast

Hey @DhanyaHerath,

I'm wondering that given Anisha's input, is this still requiring discussion?

**Comment by fergie-nz** [comment]
> Let's leave this for when @anisha-msupply is back, and then have the decision communicated across all our products - might be good to have a guideline in Storygraph.

I'm also wondering if you're needing any more actions to get this into HSH design pipeline?

**Comment by adrianwb** [comment]
> Already has a tooltip 😉
> 
> I don't like the alert on an enabled button, it means I have to click to dismiss the alert. The disabled button is a good visual cue that it isn't allowed. That's personal preference though I guess.

Absolutely agree - having to click away alerts like that is one of my pet hates about desktop mSupply - personally I prefer some visual cue e.g. different colour/style/disabled button + a tooltip, but toast is also ok as you don't need an extra click. You just need to be patient for the short time it takes to disappear again, although that might be a problem for some :-) The same goes for mandatory fields, particularly if there are multiple ones - there should be a clear visual cue. There are few things more annoying that having to go back and fill in one field, click OK and then be told that you've missed another one...

**Comment by jmbrunskill** [comment]
James Brunskill, [22/02/2024 at 12:25:04 PM]:
For the why is my button disabled problem, I wonder if we could create a component that looks visually disabled, but on click shows a tooltip/callout?
![telegram-cloud-photo-size-1-5096203491453545481-m](https://github.com/msupply-foundation/open-msupply/assets/8287373/71dbd088-d610-4ad1-a7d7-3a8775b5a032)

Probably needs a close icon option…

**Comment by mark-prins** [comment]
Have implemented the callout version, as per [this comment](https://github.com/msupply-foundation/open-msupply/pull/3307#issuecomment-2005106242)

I still like the toast though, so I'm thinking I may change to that

**Comment by AnushaUp** [comment]
# 🧪 Testing
Tested in omSupply`V2.1.0`

You may need to turn off permissions and then login again in order to properly test. I tweaked the code bc I'm lazy.
- [ ] Cold chain equipment > Create asset button
- [ ] Cold chain equipment > Add from scanner button
- [ ] Cold chain equipment > Print QR code
- [ ] Inbound returns list view > New return
- [ ] Outbound returns list view > New return
- [ ] Pack variants > Create or Delete
- [ ] Patient list view > Create patient
- [ ] Check storybook as well (`yarn storybook`) to view the example

**Comment by AnushaUp** [comment]
> [ ] Cold chain equipment > Add from scanner button

Found Issue here https://github.com/msupply-foundation/open-msupply/issues/5223

**Comment by alainsussol** [comment]
@marthakeezy 

Did you test those 2 items from that test suite while you were testing 2.4.0 ?

![Image](https://github.com/user-attachments/assets/e2ce869b-103b-42b0-b79b-a9ff801c0e63)

**Comment by marthakeezy** [comment]
Hey @alainsussol!

I can't remember - possibly did test, but gave it another go just now after seeing your mention. 

Checked with @mark-prins - permissions for printing QR code cannot be controlled from OG, so it shouldn't be in the testing suite all together. And I see the following when trying to scan an asset without permission, so I think it's working as intended?

<img width="1283" alt="Screenshot 2024-12-12 at 10 18 55 AM" src="https://github.com/user-attachments/assets/185dc59e-3371-47b4-b4ec-58d7dda7474a" />

**Comment by alainsussol** [comment]
@marthakeezy hmmm Interesting :) I am curious now, if it cannot be controlled from OG, did @mark-prins tell you where the permission is controlled from ?

**Comment by marthakeezy** [comment]
Well, from what I gathered there is no permission for printing a QR code... In OG or in omSupply

**Comment by alainsussol** [comment]
So you would always be able to print a QR code ?

**Comment by marthakeezy** [comment]
Yep, just confirmed again with @jmbrunskill!
