### ISSUE TITLE
Repack Carry Over

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#1923]
Base functionality was done in this epic: https://github.com/openmsupply/open-msupply/issues/694

Remaining Tasks:

- [ ] ~~Make sure that updating sites can see historic repack (would need to mark sync_buffer or transactions with `repack` type as needing to integrate during next sync~~
- [ ] https://github.com/openmsupply/open-msupply/issues/1432
- [ ] Ability to do remainder ?
- [ ] [Repack the whole batch ?](https://github.com/openmsupply/open-msupply/issues/694#issuecomment-1484243211)
- [x] #2530
- [x] #2539

**Comment by andreievg** [comment]
> Make sure that updating sites can see historic repack (would need to mark sync_buffer or transactions with repack type as needing to integrate during next sync

This is existing sites that went to omSupply, we don't have those

**Comment by roxy-dao** [comment]
Closing as pack variants has been removed in favour of the new item bundling.
