### ISSUE TITLE
HIV/TB Programs Go-Live

### ISSUE THREAD

**Issue by DhanyaHerath** [msupply-foundation/open-msupply#2010]
Just an epic to store the work we think needs to be done before go-live/end of the project 

**Product refinement and additional workflows:** 

- [x] https://github.com/openmsupply/open-msupply/issues/1058  
- [ ] #2061  : we are considering merging this workflow into the existing ones (HTC, ARV or both). We may want to discuss this during a meeting. The main reason is that this eRegister is adding another data entry work while you could potentially capture this data either at the enrolment (ARV) or in the Index section of the ARV encounter. Before making a decision, we need to discuss with you why the register was created in the first place so we’re not missing anything important.
    - [x] https://github.com/openmsupply/open-msupply/issues/2019
- [x] Covid-19: sounds like a very basic workflow so it should be easy to include. We were just wondering whether it is still being used ?  We also wonder if it could be interesting at this stage to include your colleagues from the EPI program to see if they would be interested in building an EIR that would work like the HIV module. We have similar plans in other countries. The COVID-19 eRegister may just be a good proof of concept for them to go ahead with routine immunisation.  https://github.com/openmsupply/open-msupply/issues/2028

**Built-in reports and national reports**

- [ ] Up to 3 reports to be confirmed

**Comment by DhanyaHerath** [comment]
@clemens-msupply @richardmoizeau Added this in for now, if you could update it after the full requirements are confirmed at your Thursday meeting that would be great!
