### ISSUE TITLE
Prescription window enhancements

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#2071]
## Is your feature request related to a problem? Please describe 👀

The 'future work' section from the original prescription epic (#1939). These are areas identified to take the MVP prescription window into being something more usable.

- [ ] #502
- [ ] Remote patient look up
- [ ] Unallocated lines and `Add from Master List`
- [x] #2091
- [ ] Delete/Alert user if navigating away without any prescription lines
- [x] #2217 Invoice status should change to `Picked` if an invoice line has been added (i.e. invoice not empty)
- [ ] Being able to `add` or `edit` patients in the prescription window
- [ ] Patient history
- [ ] Label printing
- [ ] Remote patient search
- [ ] Currency handling or receipts
- [ ] Patient notes
- [ ] Auto allocate when quantity is chosen
- [ ] Backorders
- [ ] Barcoding?

**Comment by mark-prins** [comment]
this is well covered by the PRD, #6023 and #6000
closing in favour of those

**Comment by marthakeezy** [comment]
Will be tested in the issues above outlined by Mark, moving to done ✅
