### ISSUE TITLE
Cold chain generic filters -- remaining issues

### ISSUE THREAD

**Issue by CarlosNZ** [msupply-foundation/open-msupply#2382]
Part of Epic #2282 

I'm just collecting up a list of small things that can be done to improve the generic cold chain filters -- things I've mentioned in other PRs, or just new things I've noticed. Will keep adding to this list as the remaining PRs get reviewed.

- [x] #2773 There is a block of `sx` styles that has been applied to most (all?) of the filters to get them to look consistent with a visible label, like a standard text input. It is duplicated in each one, so we can put it in a common source and re-use it.
- [x] Add an additional common prop "initialActive" -- if true, those filters will start already active in the UI. This will allow us to replicate the existing functionality, for example on "Inbound Shipments" where "Search by name" is already there. (We may even want to hide the FilterMenu too when there's only one like this?)
- [ ] #2774 Combine the common props and state/functionality for `DatePickerInput` and `DateTimePickerInput` as they're almost identical, as mentioned [here](https://github.com/openmsupply/open-msupply/pull/2379#discussion_r1362937028)
- [x] Find a sensible Regex/check to parse out "range" strings in `useUrlQuery` so we don't have to pass `parseRangeString` out from the hook. See [here](https://github.com/openmsupply/open-msupply/pull/2379#discussion_r1362939602) for more detail
- [x] Range filters should check the value of the other end of the range and adjust their limit accordingly, so we don't allow the "to" value to be lower than the "high" value (Date and Number) #2390 #2401 
- [ ] We talked about having a way to remove individual filters (not just clearing them), without cluttering the UI any further. One idea is to use a modifier -- e.g. "Option-click" on the adornment to remove them. Holding the modifier key would change the adornment icon to an "X" icon, to provide a visual indication. I realise this is kind of an "power user" feature, as you have to just know about it, but the functionality is kind of a "power user" feature, so maybe fine? Discuss if we think it's worth it.
- [ ] (Maybe?) make more common props available (e.g. width) to filter definitions. We might even want to add a "InputProps" prop, so _any_ of the inner input properties can be specified/overriden. 
- [ ] Remove the extraneous "Number" input components, as discussed [here](https://github.com/openmsupply/open-msupply/pull/2381#issue-1948753528) (Issue: https://github.com/openmsupply/open-msupply/issues/1440)
- [x] (Maybe) a separate "Boolean" filter? We can probably just use the Enum filter with true/false options, but maybe we want something that is more like a checkbox or a toggle switch? #2464

**Comment by roxy-dao** [comment]
Adding from https://github.com/openmsupply/open-msupply/pull/2412#pullrequestreview-1707316312
1) The filter bar could be more compact, e.g when going over multiple lines:

![image](https://github.com/openmsupply/open-msupply/assets/88299195/1416a376-6f88-4ad6-b1e6-03d819d0bb1d)

2) The main filter button could be smaller

3) Would be nice to have the option to remove individual filters

![image](https://github.com/openmsupply/open-msupply/assets/88299195/8e4bb9b3-80fd-4846-b152-dc33e4cce289)

However, this wouldn't work for text or date inputs. Maybe a remove button that appears if you hover the filter input?

4) The time input is different from what is used in programs. Should be the same. Maybe this one is better though because it needs fewer clicks...

**Comment by CarlosNZ** [comment]
> 3\. Would be nice to have the option to remove individual filters

What about this suggestion (from above):

> We talked about having a way to remove individual filters (not just clearing them), without cluttering the UI any further. One idea is to use a modifier -- e.g. "Option-click" on the adornment to remove them. Holding the modifier key would change the adornment icon to an "X" icon, to provide a visual indication. I realise this is kind of an "power user" feature, as you have to just know about it, but the functionality is kind of a "power user" feature, so maybe fine? Discuss if we think it's worth it.

**Comment by roxy-dao** [comment]
> > We talked about having a way to remove individual filters (not just clearing them), without cluttering the UI any further. One idea is to use a modifier -- e.g. "Option-click" on the adornment to remove them. Holding the modifier key would change the adornment icon to an "X" icon, to provide a visual indication. I realise this is kind of an "power user" feature, as you have to just know about it, but the functionality is kind of a "power user" feature, so maybe fine? Discuss if we think it's worth it.

I guess that would work but it's not intuitive enough maybe? 🤔

**Comment by mark-prins** [comment]
>  One idea is to use a modifier -- e.g. "Option-click" on the adornment to remove them.

that's too obscure for me - I would not expect anyone to discover how to make that work, or remember it if they were told!

**Comment by mark-prins** [comment]
>  (Maybe) a separate "Boolean" filter? We can probably just use the Enum filter with true/false options, but maybe we want something that is more like a checkbox or a toggle switch?

A toggle would be nice, yeah.

The handling of booleans and other primitives needs a look at too - I've just tweaked to get booleans working. it's not very elegant tho

**Comment by roxy-dao** [comment]
>Add an additional common prop "initialActive" -- if true, those filters will start already active in the UI. This will allow us to replicate the existing functionality, for example on "Inbound Shipments" where "Search by name" is already there. (We may even want to hide the FilterMenu too when there's only one like this?)

Already done just need to implement it in existing pages...

**Comment by roxy-dao** [comment]
All issues done except 

> (Maybe?) make more common props available (e.g. width) to filter definitions. We might even want to add a "InputProps" prop, so any of the inner input properties can be specified/overriden.

But we agreed that isn't needed for now.

**Comment by nisha-dangol** [comment]
Moving to Done as this can be tested as part of #2282
