### ISSUE TITLE
Carry over for Berlinger fridge tag integration

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#2423]
From this epic:  https://github.com/openmsupply/open-msupply/issues/1798
And this issue: https://github.com/openmsupply/open-msupply/issues/2420 and this PR: https://github.com/openmsupply/open-msupply/pull/2422

** Front End **

- [x] Better way to display errors and success, and stop user being able to refresh the page and re-upload, when upload is in progress (see todo in [this file](https://github.com/openmsupply/open-msupply/blob/ace39473bee622bf6d71d99bf59e71e505122b6d/client/packages/coldchain/src/Sensor/ListView/AppBarButtons.tsx)) #2592
- [x] Is the button in the right place ? (No - move to logs section and add prompt for user to add location on first import) #2592
- [X] Is the button labeled correctly ? See #2508 
- [x] Add some subtext to button to explain that user can also import Q-tag logs #2592
- [x] Restrict upload input to .txt #2592
- [x] Use different icon for button:  https://github.com/openmsupply/open-msupply/pull/2422#discussion_r1381051855 #2592

** Back End **

- [ ] https://github.com/msupply-foundation/open-msupply/issues/2597
- [ ] https://github.com/msupply-foundation/open-msupply/issues/2598
- [ ] Add store_id to the service context, rather then passing around as parameter to read_sensor
- [ ] Do we need to make integration functionality async (run in spawn_blocking ?)
- [x] #2532
- [x] Create tag for temperature_sensor crate, and use that as dependency [added v0.1.0-beta.1 & .2 tags - Adrian]
- [ ] Add service tests, probably at the end of the file here ? https://github.com/openmsupply/open-msupply/blob/30565a83a4e4db774d6ba195650a75ee5842afab/server/service/src/sensor/berlinger.rs
- [x] Link logs to breaches, as per this one: https://github.com/openmsupply/open-msupply/pull/2383#issuecomment-1787689587 - #2594
- [ ] https://github.com/msupply-foundation/open-msupply/issues/2599

** Auto Detect Sensor and Multiple Sensors Upload Simultaneously **

- [ ] Capacitor and Electron to check USB is plugged in and that it matches berlinger file type
- [ ] Some UI to indicate that sensor is plugged in and needs to be synced 

There is a slights misalignment, noted in [this comment](https://github.com/openmsupply/open-msupply/pull/2383#issuecomment-1791569367), @adrianwb is leaning towards multi sensor integration at once functionality (and there is actually code in temperature-sensor crate for it), I think it doesn't need to be done, I can't see a use case for one button integrate all plugged in sensors. Can we get an opinion on this please @craigdrown @mark-prins @adamdewey  ?

**Comment by adamdewey** [comment]
Sorry @andreievg, missed this somehow. 

> Is the button in the right place and is it labeled correctly ?

No and no 😁

Will make update to the label via the translation server as suggested by Mark in #2508 

I also think the button would be better served in the `Monitoring > logs` section. 
And perhaps the first time a Fridge-tag is connected there could be a pop-up telling the user that a new sensor has been registered (and prompting them to assign a location before they do the initial import)

**Comment by adamdewey** [comment]
> There is a slights misalignment, noted in https://github.com/openmsupply/open-msupply/pull/2383#issuecomment-1791569367, @adrianwb is leaning towards multi sensor integration at once functionality (and there is actually code in temperature-sensor crate for it), I think it doesn't need to be done, I can't see a use case for one button integrate all plugged in sensors. Can we get an opinion on this please @craigdrown @mark-prins @adamdewey ?

Also can't see a use case for it at this stage - I think the average end user would expect to just plug in one Fridge-tag at a time and import the data one after the other.

**Comment by adrianwb** [comment]
> Location should be linked to fridge tag differently to how it's linked to blue maestro, since the former is uploaded less frequently. We thought about adding a modal when fridge tag data is integrated, to allow user to select location. Maybe simpler solution for now is to back date selected location for temperature logs and breaches when it's selected ? But then how do we manage when location is cleared ? When say fridge tag is moved to another sensor. And also how do we manage sensor down time (when say it's not in a fridge for a bit ?). Btw we've settled on setting and removing location as the way to tell the system that sensor is inactive/active (for like battery change and relocation)

The basic problem is that when you first import a sensor, there's no location set, even though it's likely that the sensor has already been in a location up to that point => the only way I can see to get around that is to force the end user to set a location  at the point of import (or leave it blank if it truly hasn't been anywhere yet)? Or we just do as desktop does and assign any pre-existing logs which don't already have a location to the location when the sensor is assigned?

Moving a sensor complicates it even more - obviously we can't change historical logs for the old location, but it's likely that there will be some logs saved between moving from the old location to the new one => maybe make it inactive before the move (and set the location to blank)?

Whatever we do, I think we need a clear SOP which defines how to handle each stage e.g.:
- for a new sensor, import it as inactive to start with and set its location to blank
- make it active by assigning a location; and subsequent import logs will have that location
- if planning to move it, then make it inactive first and set its location back to blank
- once it has been moved, make it active again by assigning the new location

There will be some temperature logs created while the tag is outside the fridge and being imported, but they can usually be ignored as it should never be out long enough to trigger a breach

**Comment by adrianwb** [comment]
> > There is a slights misalignment, noted in [#2383 (comment)](https://github.com/msupply-foundation/open-msupply/pull/2383#issuecomment-1791569367), @adrianwb is leaning towards multi sensor integration at once functionality (and there is actually code in temperature-sensor crate for it), I think it doesn't need to be done, I can't see a use case for one button integrate all plugged in sensors. Can we get an opinion on this please @craigdrown @mark-prins @adamdewey ?
> 
> Also can't see a use case for it at this stage - I think the average end user would expect to just plug in one Fridge-tag at a time and import the data one after the other.

For the current setup, then one at a time makes sense where the client is doing the import by choosing a file. The multiple sensor import case was more for if you had multiple USB (or other) sensor files connected to a server and the server was doing the import => agreed that we don't currently need it, although it'll do no harm to leave that functionality in the `temperature-sensor` crate for the future or if other users want to use the crate in a different way.

**Comment by adamdewey** [comment]
I think we can make our lives easier by imagining the most likely scenarios in the real world. 

For the most part I would imagine the same Fridge-tag is used in the same fridge over an extended period of time. We can call this scenario 1:

- 1 - The Fridge-tag is used in the same location repeatedly.

For scenario 1 it would be great to prompt the user to enter a location on the first import and then to remember that location for subsequent imports. 

The other, less common scenario, is that they move the Fridge-tag to monitor a different fridge.
This scenario could be further broken down into:

- 2a - the user waits 30 days before importing from the new location. 
- 2b - the user doesn't wait 30 days before importing from the new location

In these scenarios the user should select a new location before doing the import. For 2a everything should work perfectly, for 2b they'll drag over some data from the old location. 

As we can't automatically detect a change in location we have to rely on the user to do the right thing. 

We can try and guide them to do that though! 

My thinking is that we can weigh us these 2 alternatives: 

- Make the user's life easy for the most common scenario 1 by remembering the previous location.
  - Risk: User may forget to change location for first import from new location.

- Force user to enter location for each import
  - Risk: system is annoying to use

I would tend to lean towards the first option as I would imagine it will be quite a rare occurrence for the Fridge-tag to move to a new fridge and try to mitigate the risk of forgetting to change the location via an SOP as Adrian suggests?

**Comment by andreievg** [comment]
Closing this carry over, important tasks are captured in issues already, and the auto detect USB etc will need to be re-raised if it becomes a feature request
