### ISSUE TITLE
Open mSupply Record Merging 

### ISSUE THREAD

**Issue by Chris-Petty** [msupply-foundation/open-msupply#2450]
## Is your feature request related to a problem? Please describe 👀

[Based on the Legacy mSupply KDD regarding merge strategy.](https://github.com/msupply-foundation/msupply/blob/6342dba1ac0aacf010078ce4478c58d67f545916/decisions/0005-sync-v5-merges.md)

Open mSupply must support record merging in the following areas:
 
- [x] #2451
- [x] #2550
- [x] #2551
- [x] #2552
- [x] #2553
- [x] #2639
- [x] #2554
- [x] #2620
- [x] #2626
- [x] #2635
- [x] #2636
- [x] #2637
- [x] #2452
- [x] #2555 
- [x] #2556
- [x] #2557 
- [x] #2558 
- [x] #2559
- [x] #2681
- [x] #2732 
- [x] #2735 
- [x] #2682
- [x] #2683
- [x] #2684 
- [x] #2754
- [x] #2561 
- [x] #2562  
- [x] #2606 
- [x] #2815
- [x] #2745 
- [x] #2746
- [x] #2747 
- [x] #2748  
- [x] #2749
- [x] #2750 
- [x] #2767
- [x] #2771
- [x] #2454
- [x] #2565 
- [x] #2566 
- [x] #2769
- [x] #2607 
- [x] #2698
- [x] #2733 
- [x] #2759
- [x] #2833
- [x] #2835 
- [x] #2836 
- [x] #2837 
- [x] #2838 
- [x] #2839 
- [x] #2840 
- [x] #2841 
- [x] #2842  
- [x] #2843 
- [x] #2844 
- [x] #2845 
- [x] #2846 
- [x] #2847 
- [x] #2848 
- [x] #2849 
- [x] #2850 
- [x] #2885

### Additional context 💌

Will be using `someTable_link` format for each merge-able table. An alternative would be `link` with `link.type = "someTable"` but it is more difficult to setup SQL FK constraints when done that way.

Additional areas that could require merging support in the future:

- #2453
- Store merging
- User merging 

### Moneyworks Jobcode 🧰

OMS:MERGE

**Comment by Chris-Petty** [comment]
Hey @clemens-msupply, thanks for merging with the merge squad! Or at least till something pressing comes up for you 😁.

At the moment I'm focusing on the item merging (and might be on a side track to fix the speed of Legacy mSupply merge...) - it'd work pretty nicely if you wanted to work on the name merge issues in the epic here - top down is a good order. Happy to have a chat if you want a boost into the context, otherwise the PRs for each issue break down what needs to happen if you want to look at the previous changes for an example (most of the PRs are very similar but for different tables).

**Comment by nisha-dangol** [comment]
# Testing
Testin in v1.7-rc3

- [x] mSupply Desktop Central Server (MDCS) and an OMS android or desktop. Synced, but with OMS on an older version (I took v1.6.3) (without these changes - we want to ensure migration works correctly)
- [x] Merge 2 items and merge 2 names on MDCS and sync. (This will ensure there are unprocessed merge records in the integration buffer of OMS)
- [x] Migrate OMS to the latest version including these changes
- [x] Check:
  - [x] Item catalogue updated
  - [ ] Master lists updated - FAILED : #3306 
  - [ ] Stock take lines updated 
  - [ ] Stock lines updated
  - [ ] Requisition lines updated
  - [ ] In/outbound shipment lines and prescription lines NOT updated (the original name when the line was added should be preserved)
- [x] Check the names appear merged in
  - [ ] Customers - Bugs found: #3449 
  - [ ] Suppliers - bugs found
  - [ ] Shipments referencing merged name - **I see some merge fails, but can't replicate again, so checking!**
  - [ ] Internal orders/Requisitions **Tricky, you probably don't have any to the merged name as you can't merge store names! And you can't make these records to regular names/external parties in OMS... yet**
  - [ ] Prescriptions
  - [ ] Barcodes
  - [ ] Patient encounters
- [ ] Do all of the above again merging the kept name into another name and the kept item into another item - checking that merge on regular sync works correctly, not just after migration.
- [ ] Spicy edge case: Make a customer invoice to a regular name. Merge that name into a store that is active on your OMS site. Sync. Login to that store and check that a supplier invoice has been created. (Note, you can in effect make a SI to your own store in doing this. Not ideal, but currently expected behaviour. Should be rare...)

**Comment by nisha-dangol** [comment]
Regarding the preserving merged items in invoices, @anildahalsussol says that once merged, the merged items will be taken over by the kept item in invoices and prescriptions as well. 
With this expected-behavior in mSupply, shouldn't we expect the same in oms as well? @mark-prins @Chris-Petty ?

**Comment by Chris-Petty** [comment]
@nisha-dangol @anildahalsussol 

Invoices maintain the item name:

https://github.com/msupply-foundation/open-msupply/assets/7684221/20acfe6f-4b55-47d0-8e6a-6342338c4611

On unfinalised invoices I believe it's meant to be possible to refresh the item name by editing it. There appears to be a bug though at the end of the vid where I try that and the KEPT item name gets replaced by the deleted item name somehow.

Finalised prescription:


https://github.com/msupply-foundation/open-msupply/assets/7684221/721b87ab-bbda-43f7-a71b-78f057cf6912


The item name is maintained for clearer history of the information in the system at the time of the transaction. As the transact is finalised you should not be able update the line info.

This is implemented by `trans_line.item_name` which maintains the name at the time the trans_line was made, rather than using `trans_line.item.name` which does indeed change after merging (because the item changes). OMS should do the same (it does in my testing). OMS goes a little further and preserves the item_code too, which I think is great:

https://github.com/msupply-foundation/open-msupply/blob/e047487c9197b20467c0d1a6e3ef5bf73345361a/server/repository/src/db_diesel/invoice_line_row.rs#L20-L21

**Comment by nisha-dangol** [comment]
I'm on v7-13-00 exe and the merged item is replaced by the kept item in both CI or prescription in mSupply:
Here's video references for you: 
1. https://recordit.co/ezXiE8cerG
2. https://recordit.co/Yxc4h7RWDj

**Comment by Chris-Petty** [comment]
@richardmoizeau @craigdrown can one or both of you  please clarify desired behaviour when item names in various contexts should be updated when a merge occurs:

- new prescription
- confirmed prescription (note - I believe labels may already be printed at this stage)
- finalised prescription
- suggested customer invoice (/supplier credit/inventory reduction)
- confirmed customer invoice
- finalised customer invoice
- suggested supplier invoice (/customer credit/inventory addition)
- confirmed supplier invoice
- finalised supplier invoice
- Stock takes?
- Requisitions?
- Purchase Orders?
- Goods Receipts?
- Tenders?

**Comment by nisha-dangol** [comment]
> @richardmoizeau @craigdrown can one or both of you please clarify desired behaviour when item names in various contexts should be updated when a merge occurs:
> 
> * new prescription
> * confirmed prescription (note - I believe labels may already be printed at this stage)
> * finalised prescription
> * suggested customer invoice (/supplier credit/inventory reduction)
> * confirmed customer invoice
> * finalised customer invoice
> * suggested supplier invoice (/customer credit/inventory addition)
> * confirmed supplier invoice
> * finalised supplier invoice
> * Stock takes?
> * Requisitions?
> * Purchase Orders?
> * Goods Receipts?
> * Tenders?

Moving this to new issue [here! ](https://github.com/msupply-foundation/open-msupply/issues/3556)
