### ISSUE TITLE
Currency support

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#2630]
## Is your feature request related to a problem? Please describe 👀

The currency symbol shown throughout the site is tied to the language used. The `useCurrency` hook is matching the current language to lookup `currencyOptions` which gives an object of the shape:

```
en: {
    symbol: '$',
    separator: ',',
    decimal: '.',
    precision: 2,
    pattern: '!#',
    negativePattern: '-!#',
    format,
  }
```
Where the `!` is replaced with the symbol and `#` with the value in the formatting patterns.
We need to separate the linking of currency, while retaining the regional formatting, which could potentially be linked to language.

We will also support [multiple currencies](https://docs.msupply.org.nz/other_stuff:currencies) and [foreign currencies in transactions](https://docs.msupply.org.nz/other_stuff:foreign_currency_transactions#supplier_invoices) similar to the mSupply implementation.

## Describe the solution you'd like 🎁

- Separate language and currency
  - [x] #2795 sync the `currency` table
  - [x] #2807 
  - [x] #2827 use the 'home currency' to dictate the default currency and continue to use a lookup of currency formats, using the ISO currency codes as the key
- Support multiple currencies
  - [x] #2800 bring through the `store` preference for support of foreign currencies
  - [x] #2831 sync the selected currency of names
  - [x] #2865
  - Show additional columns, add the selection of currency and convert values for:
    - [x] #2830
    - [x] #2903 
    - Supplier returns (if implemented by the time we do this!)
    - Customer returns (if implemented by the time we do this!)

- [ ] #2910 

Carry over 
- [x] #3084 
- [x] #3134 
- [ ] Make `currency_id` not null in 1.8
