### ISSUE TITLE
Asset Management Module for CCE Inventory: Phase 1

### ISSUE THREAD

**Issue by DhanyaHerath** [msupply-foundation/open-msupply#2896]
## Background Information

The goal of asset management is to digitize the creation and maintenance of an asset register, to enable health departments to keep track of, and manage, and maintain assets which enable their operations. 

_A subset of asset management is Cold Chain Equipment Inventory (CCEI) management. In the immunization sector there is a strong drive to improve the management of CCEI._

Current CCEI pain points: 
- “We have no idea of the available, functioning capacity of cool storage in the national supply chain”
- “CCEI is recorded on spreadsheets, so there's no visibility of it once it's been distributed. Sometimes things go missing or get damaged and no-one at central knows. People take coolers home to store their drinks in.”
- “We find it really hard to keep CCE, such as fridges and freezers, working, and to fix them in a timely manner once they break”

Problems to solve:
- Easily add assets in omSupply
- No visibility over regional stores
- No feedback on which assets are: 
  - Installed / not installed
  - Working / not
- No visibility of real-time available cool storage volume per facility
- CCE keep breaking (and then stay broken for extended periods)

### Documents
- [Product design document](https://docs.google.com/document/d/1k0ZOls0sFSF85eZga0imk6ztx7IbATFf5ETC5y4oHKw/edit)
- [Figma designs](https://www.figma.com/file/rIK2zVFUVhtbuXo0RBzOzw/0033-2305_omSupply-ColdChain-UI?type=design&node-id=2653-16424&mode=design&t=8KRUuAo7s1V0r0RM-0)

### Database structure

The reference data (WHO PQS catalogue by default) is defined by an `asset_catalogue_item` which is classified by type, category and class with the hierarchy below.

An `asset` is created from an `asset_catalogue_item` and so will inherit the type, category and class

[![](https://mermaid.ink/img/pako:eNqdVMFOxCAU_BXCefcHejDR6G31Yrw1aZ7wupIA3dBHYlP770K3a7qUbVUuLfPmDQND6LloJPKCCw1t-6jg6MCUloUR5kiVAMJj4zq233_dXbDInZOoO-EVYWpKhEA3R4-VIjSrcivUPwlHWzNmIjRrukVKjG04yS89imRX7dmZEQfhJzElEyBmk0AzZ9WCf21tWX95OxzuHw5PM5NLkgHraxDkHbq0FPzoMzZkdhf_-0tLsqNxasHg7fbJ9i8VVs4jIx63-i_h9CyX2qzfirGlxmUOer7k7cB_MmvRKdCV9eZ9EcxW8Gt5567mFUsGWaZsGwgaSDW2ikhSd3jSINCgpUyZlEEW7g4SyuoCZCjCIWxQwh1UtVpwBr7jBp0BJcNrNkZScvoIhkpehF-JNXhNJS9tpIKn5rWzghfkPO64P0W56f3jRQ26DShKFaJ7nl7I-Bm-ASgNtds?type=png)](https://mermaid.live/edit#pako:eNqdVMFOxCAU_BXCefcHejDR6G31Yrw1aZ7wupIA3dBHYlP770K3a7qUbVUuLfPmDQND6LloJPKCCw1t-6jg6MCUloUR5kiVAMJj4zq233_dXbDInZOoO-EVYWpKhEA3R4-VIjSrcivUPwlHWzNmIjRrukVKjG04yS89imRX7dmZEQfhJzElEyBmk0AzZ9WCf21tWX95OxzuHw5PM5NLkgHraxDkHbq0FPzoMzZkdhf_-0tLsqNxasHg7fbJ9i8VVs4jIx63-i_h9CyX2qzfirGlxmUOer7k7cB_MmvRKdCV9eZ9EcxW8Gt5567mFUsGWaZsGwgaSDW2ikhSd3jSINCgpUyZlEEW7g4SyuoCZCjCIWxQwh1UtVpwBr7jBp0BJcNrNkZScvoIhkpehF-JNXhNJS9tpIKn5rWzghfkPO64P0W56f3jRQ26DShKFaJ7nl7I-Bm-ASgNtds)

### Issues 
- [x] #2955
  - create/edit/delete asset classes, categories, types and catalogues
  - view(is this required?)/edit the catalogue
  - view/edit the asset register

#### Central server only
- [x] #2958
- [x] #2959
- Administer classes of assets
  - [x] #2960
- Administer types of assets
  - [x] #2963
- Administer categories of assets
  - [x] #2966
- Asset catalogue
  - [x] #2956
  - [x] #2969
  - [x] #3083
  - [x] #2970

#### All open mSupply
- Asset register
  - [x] #2972
  - [x] #2973
  - [x] #2974
  - [x] #2975
  - [x] #2976
  - Detail view
    - [x] #2977
    - [x] #2978
    - [x] #2979
    - [x] #2980
    - [x] #2981
  - [x] #2982
  - [x] #2983
  - [ ] Cold chain reporting? there's mention of 'print' and 'cold chain report'. what is this?
  - [x] #2984
  - Log tab
    - [x] #2985
    - [x] Query for asset log reasons?
    - [x] #2986
    - [x] #2987
    - [x] #3204 
  - [x] #2988
- Available cold storage
  - [x] Data collection?
  - [ ] Make report?
- Sync and visibility
  - [x] Health centres only see assets assigned to their store
  - [x] #3159  Central server / MOH staff / CCE technician can see all assets

### Moneyworks Jobcode 🧰
We have 512 days of work available for this: 

OMSCC:AST

**Comment by mark-prins** [comment]
Merged in now! 🎉
