### ISSUE TITLE
Supplier/Customer Returns

### ISSUE THREAD

**Issue by DhanyaHerath** [msupply-foundation/open-msupply#2897]
# Design docs

https://docs.google.com/document/d/1szgYLDM-euSgpp9IdWom8K_OYJoxxENADiExBObjJKA/edit?usp=sharing

# Tasks

#### I think we should start with return from existing inbound/outbound shipments, with mock api

- [x] Can select lines from inbound shipment for outbound return (1h) #2921 
- [x] New return items UI (with all selected lines), for outbound return (8h) #2921 
    * Api should really provide anything that is required for return items view, based on provided ids of lines
- [x] A reason step in return items UI, for outbound return and create return on OK (5h) #2929 
    * Api to post stock line id, reason and comment, which in turn creates return (and returns it in API call)
- [x] Outbound return detail view (12h) #2920
    * Would be the same as invoice query ?
- [x] Can select lines from outbound shipment for inbound return (1h) #2944 
- [x] New return items UI (with all selected lines), for inbound return  (8h) #2944 
    * Api should really provide anything that is required for return items view, based on provided ids of lines
- [x] A reason step in return items UI, for inbound return and create return on OK (5h) #2950 
    * Api to post stock line id ? (or outbound line ids? or full info about batch/expiry, quantity etc.. ?) reason and comment, which in turn creates return (and returns it in API call)
- [x] Inbound return detail view (12h) #3163 
     * Would be the same as invoice query ?

#### Then list and creating new returns, and selecting items

- [x] Outbound return list view (5h) #2953
  * Api i think just new type of invoice
- [x] Inbound return list view (5h) #2998 
  * Api i think just new type of invoice
- [x] Add new outbound return from list (3h) #3008 
  * Same as outbound/inbound ?
- [x] Add new inbound return from list (3h) #3014 
  * Same as outbound/inbound ?
- [x] Add new line (by item) to outbound return (from existing batches) (8h) #3022 
  * Would prefer API to be a lot more direct here then how it's down in inbound/outbound
- [x] Add new line (by item) to inbound return (from previous outbound shipments or manually) (8h) #3189 
  * Would prefer API to be a lot more direct here then how it's down in inbound/outbound
- [x] Change statuses (2h)
- [x] Print (4h) #3190 

#### Synchronisation and transfers (creating inbound return from outbound return, in omSupply site) 

- [x] Add schema changes for outbound/inbound return record type, make sure they are syncing (3h) #3056
   * New invoice type
   * New reason table (duplicate inventory adjustment reason _row)
   * Return reason id on invoice_line table ?
   * Comment on invoice_line table
- [x] Generate the other 'half' of outbound/inbound return with processors (8h) #3191

#### API implementation

For outbound return we must reduce stock according to status (similar to outbound shipment)

- [x] generateOutboundReturnLines (5hrs) #3043
   * Look up stock line by ids union with stock line by item_id -> populate OutboundReturnLineNode
   * If existing return is specified, populate reason + comment + numberOfPacks from invoice_lines in the existing return
- [x] generateOutboundReturnLines (item_id and return_id) (3hrs - new estimate) #3144 
- [x] insertOutboundReturn (3hrs) #3059
   * Similar to other invoice inserts (outbound insert)
   * Number series
   * Can probably use `insert_stock_out_line` in service
- [x] updateOutboundReturnLines (8hrs) #3081 
   * This one will use combination of stock_out_line/delete + update +  insert, we don't need item_id at all, please delete (when input numberOfPacks = 0 then delete line)
- [x] deleteOutboundReturn (1hrs) #3132
   * Delete and make sure to release reserved stock in stock lines (see outbound delete for example)
- [x] updateOutboundReturn (6hrs) #3121 
  * Similar logic to outbound_shipment update (in terms of stock movements)

For inbound return we must add stock according to status (tempted to consolidate logic for incoming stock similar to outgoing stock, i.e. service/source/invoice_line/stock_out_line/

- [x] generateInboundReturnLines (5hrs) #3155 
- [x] insertInboundReturn (3hrs) #3181
- [x] updateInboundReturnLines (8hrs) #3183
- [x] deleteInboundReturn (1hrs) #3186
- [x] updateInboundReturn (6hrs) #3185

Additional work:
- [x] Add permission checks, and sync them (5hrs - new estimate) #3187
- [ ] A better name for the generateLines queries - it's not clear what this does + other naming fixes (3hr) #3188
- [x] In the modals, we have 2 steps. We filter the table rows of the second step to only include the rows that had a "quantity to return" set in step 1. If we zero out all the lines, this is weird UX. Discuss with PO? (2hr)
- [x] Ability to go back to previous step in modals ([see more](https://github.com/msupply-foundation/open-msupply/pull/3041#discussion_r1508457976)) (2hr) #3192 
- [x] Link a shipment and a return #3299 
- [ ] Additional fields - we created the modals with minimal inputs, but especially for inbound returns, need to add pricing and location inputs!

# Overview

Please see **Design docs** for a comprehensive description of this feature.

Outbound returns and inbound returns are very similar to inbound and outbound shipments in how they look and how they behave. 
Outbound return is like an outbound shipments, except there is a 'reason' page in item edit detail view modal. And the inbound return is like inbound shipments, except again for the reason.

There is an ability to create outbound return from inbound shipment and inbound return from outbound shipment, be using the side select and drop down, which would navigate to item edit detail modal with ALL of the lines that were selected, this is a different view (previously this view was just for one item, this could be for multiple items).

Return statuses should be the same as shipments (to clarify).

What about linkable between outbound -> inbound -> outbound return -> inbound return

Finalised inbound and outbound shipments only for now

# API

We should try to do consumer based approach (see Addition context), but I think it's worth re-using existing types like 'invoice' and 'invoice-line'

Added draft API diagrams in [this branch](https://github.com/msupply-foundation/open-msupply/compare/develop...develop(Return-api-diagrams))

Outbound Return

![api-flow-supplier-return](https://github.com/msupply-foundation/open-msupply/assets/26194949/ed2d3b2d-4519-43af-9fd3-1019d65c1a5c)

Inbound Return

![api-flow-customer-return](https://github.com/msupply-foundation/open-msupply/assets/26194949/a5f98d24-10fe-4ab6-9b82-ed67711ef869)

The big difference between current API for shipments and the proposal, is that in the proposal we don't have to maintain draft state, and just push the snapshot of the current view to API

### Additional context 💌

We are going to try consumer based API approach for this feature, which means doing UI first with a mock API on back end (mock API is pure grahpql, with mock data, no logic). We will also cater API for each view (i.e. rather then having batch mutation of inserts, update and deletes etc, we would have one mutation for the details modal <- where the lines are added and removed).

Also trying to do the minimum number of details, and just do the skeleton first (minimum number of columns) etc.. So we can run the full workflow past stakeholders ASAP

Is this a good time to try pagination for detail view ?

### Moneyworks Jobcode 🧰

OMS:CDIDV

**Comment by lache-melvin** [comment]
Questions: 

- [ ] Statuses: New > Picked > Shipped > Delivered > Verified - do we need Picked? 
  - [ ] Confirming there should be no Allocated status? Shouldn't be possible as you are returning specific stock, wouldn't have placeholder lines... 
- [ ] Should we be able to put returns on hold?
- [ ] Should they have colour (like shipments)?
- [ ] Should you be able to change the other party once created? e.g. start a return, then decide to return to different supplier?
- [ ] Should a return reason be required, or optional?

**Comment by DhanyaHerath** [comment]
I think [these questions above](https://github.com/msupply-foundation/open-msupply/issues/2897#issuecomment-1987383524) are for @richardmoizeau  - though let me know if you want me to look through instead Richard!

**Comment by richardmoizeau** [comment]
>Statuses: New > Picked > Shipped > Delivered > Verified - do we need Picked?
 Confirming there should be no Allocated status? Shouldn't be possible as you are returning specific stock, wouldn't have placeholder lines...

That's a good question. Technically, you need to pick the items (as in prepare the order) that you want to return but to be honest, it would more for medium to large warehouses, Health Facilities would probably only create a new return and ship it. We can discuss this in our internal meeting. 

> Should we be able to put returns on hold?

the on hold option is usually used in OG to allow one authorised user to finalise the transaction while somebody else without the permission can prepare (up until picked). 

> Should they have colour (like shipments)?

Nice to keep it consistent :)

> Should you be able to change the other party once created? e.g. start a return, then decide to return to different supplier?

only for "unlinked" return you should be able to select another supplier once shipment is created. For "linked" returns, it should be returned to the same supplier recorded in the related (or linked) inbound shipment. 

> Should a return reason be required, or optional?
Very good question ! Sorry the design docs were not clear enough on this. There should be a way on the server to set the reasons as optional. Currently for stocktake in OmSupply, you either have mandatory reasons or not at all. Another point to discuss in our meeting. 

> What should we do if no return reasons have been configured?

Ideally, we should not show "step 2" (or tabs "reasons comments"). 

>  Wizard steps vs the tabs from shipments?

another good one for our upcoming discussion. Steps were implemented to better fit the use tablets.

**Comment by lache-melvin** [comment]
Closing as complete for v2.0.0, carry over work captured here: #3721
