### ISSUE TITLE
Remaining Number Input issues

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#2932]
EDIT: As well as the below problem, there are a few other implementations around where the logic of the parent components still needs updating to work with the new input component (from #2794).

Let's use this issue to list them all as we find them and I'll sort them out all at once. Please add to the checklist here, and put any further detail/screenshots etc in comments below. Thanks.

- [x] Problem clearing # packs (below) (something is turning it into `type="number"` from above which is odd, too)
- [x] Still have a couple of `type="number"` attributions in Programs that should be removed
- [x] [Inbound shipment pack quantity](https://github.com/msupply-foundation/open-msupply/issues/2932#issuecomment-1942859584) should just be a NumberDisplayCell (i.e. not editable)
- [x] [French currency formatting of thousands test failing](https://github.com/msupply-foundation/open-msupply/issues/2932#issuecomment-1944492789)
- [ ] See if "react-currency-input-field" can be removed and just use the built-in IntlNumber.format() function to do what we want
- [ ] [The separator for EU should be  but input always ends up adding , for the last two numbers even if you are not typing a decimal?](https://github.com/msupply-foundation/open-msupply/issues/2932#issuecomment-1963032660)
- [x] [Decimal doesn't work beyond 2 dp](https://github.com/msupply-foundation/open-msupply/issues/2932#issuecomment-1963048439)

## What went wrong? 😲
 

https://github.com/msupply-foundation/open-msupply/assets/55115239/40ac1ca7-4693-48ab-a706-834fbf2aa50d

I'm passing in props that this should be a required value with a minimum of 1, but clearing the input results in NaN, which I can then clear to nothing...

I think this is broadly an issue with the `NumberInputCell`, as I've seen this issue in at least Inbound Shipment, Stocktake and new Supplier Returns so far...

## Expected behaviour 🤔

Clearing the input sets the value to 0, or the minimum value if min>0.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to an Inbound Shipment details page
2. Click on a line to edit
3. Clear the # packs input
4. See `NaN`
5. Clear the `NaN`
6. See nothing in the input

## Your environment 🌱

 - Version: 1.6.x (develop)
 - Platform: browser (Chrome)

**Comment by lache-melvin** [comment]
Interestingly (fortunately) enough, submitting the modal with the value as NaN or empty doesn't cause a mutation of that line!

**Comment by lache-melvin** [comment]
![Screenshot 2024-02-14 at 12 08 53 PM](https://github.com/msupply-foundation/open-msupply/assets/55115239/09143c04-03a2-450d-8407-2b7845f78ab5)

Inbound shipment pack quantity is an input cell? For mouse users its kind of fine because clicking it opens the modal rather than focussing the input.

However you can tab to it, and editing the value crashes the page:

![Screenshot 2024-02-14 at 12 40 45 PM](https://github.com/msupply-foundation/open-msupply/assets/55115239/b62ef049-bb3e-4084-bb8a-009557dc91e1)

**Comment by lache-melvin** [comment]
French currency formatting of thousands test failing:
![Screenshot 2024-02-15 at 8 51 59 AM](https://github.com/msupply-foundation/open-msupply/assets/55115239/4dea6e28-f715-4092-888a-749656ba4e4d)

**Comment by roxy-dao** [comment]
Input goes to NaN and then I can't enter anything anymore...
https://github.com/msupply-foundation/open-msupply/assets/61820074/feb797da-8cda-4ab6-9aa3-f4ec805b265f

**Comment by roxy-dao** [comment]
None of the decimal inputs work.... also the separator for EU should be `.`?
![Screenshot 2024-02-23 at 16 05 34](https://github.com/msupply-foundation/open-msupply/assets/61820074/c104d3d7-2278-461b-a75e-55a1e35a31ed)

**Comment by roxy-dao** [comment]
Decimal doesn't work beyond 2 dp

**Comment by CarlosNZ** [comment]
> The separator for EU should be ` ` but input always ends up adding `,` for the last two numbers even if you are not typing a decimal? 

This is just [this existing issue](#2918)
