### ISSUE TITLE
Inventory Adjustments -- overview

### ISSUE THREAD

**Issue by CarlosNZ** [msupply-foundation/open-msupply#3466]
**To be broken out into individual issues as/when required**

After some team discussion with @craigdrown and @richardmoizeau, we agreed on the following course of action:

Basic overview is that individual stock-line adjustments can be done using the View Stock UI, but larger adjustments (e.g. removing all expired stock) should be done via existing stocktake functionality

### View Stock UI
![Screenshot 2024-03-28 at 10 59 32 AM](https://github.com/msupply-foundation/open-msupply/assets/5456533/66fd0871-7e07-4c51-b589-519f632e2e05)
- In "View Stock", make the "quantity" for each line editable. When the value is changed, a new "Reasons" selector appears, which must be entered before changes can be made.
- The change would appear in the "Log" tab
- _To consider_: ideally, there would be a way to just enter the *changed* amount (e.g. "I'm throwing out 3 boxes") without having to do the mental arithmetic to subtract the reduction from the current quantity. It would be possible to accept a negative input value in the input field, which would then alter the quantity, but this might be too advanced/technical for users -- @richardmoizeau to ask. Other suggestions welcome.
- An "Add stock" button on the main list view where *additional* stock lines can be added. Would require an Item selector initially, which would become the standard (above) stock line modal after selection.
- Update "Expiry date" filter to default to "Today" for the "TO" field

### Stocktakes
- When starting a new stocktake, the modal should have an "Expired items" option (along with Master lists, etc). When this option is selected, the new stocktake is created with quantities defaulted to "0".

## Subsequent To-Do:
- Additional "Ledger" tab on stock line modal (in screenshot above)
- When adding a new batch, some way to alert the user if the batch already exists (with 0 quantity). Mechanism/functionality to be determined
- In Stocktake detail view, add a "Set quantities to 0" action to the Actions drop-down

## Future nice-to-haves/considerations
- When adding a new adjustment, an existing problem is price -- people forget to add it. A mechanism to pre-fill a sensible price based on current items would be desirable (exact calculation to be determined)
- Reports: while we could add a new list view to show all Inventory Adjustments, it was thought that this could/should be a report. Other reports (examples to be added) can also be implemented.

# Tasks

## Expired through stocktake

- [x] #3502
- [x] #3503

- [ ] Actions on view stock page (idea for future)

## Quickly Add/Reduce stock for existing stock line (single)

- [x] #3496
- [x] #3497
- [x] #3498
- [x] #3499

## Add new stock line (single)

- [x] #3500
- [x] #3501

- [ ] Search existing ? For duplicates ? And for prices matches
   - [ ] Auto complete on batch field
   - [ ] On loose focus on batch field ? Show warning with navigation to stock table with those filters applied

## Extra

- [x] #3604

**Comment by CarlosNZ** [comment]
Do we need to consider permissions? Can anyone make stock adjustments or only certain users?

**Comment by lache-melvin** [comment]
> * In "View Stock", make the "quantity" for each line editable. When the value is changed, a new "Reasons" selector appears, which must be entered before changes can be made.

Another idea: Instead of quantity being editable, we have some kind of `adjust` button next to it, which opens another modal to do the inventory adjustment in.

Pros:
- More space for something like an `adjust by` field (could have `current`, `adjust by`, and `new total` - user can update `adjust by` or `new total` depending on which would be easier in the situation, the other field will update automatically`)
- Reasons can be inputted here (less conditional rendering in the main modal view - also make it easier to reason about when OK buttons can be clicked)

Cons:
- Pretty sure we've been trying to avoid modal in modal
- Might be faster for first iteration to just edit existing modal?

**Comment by roxy-dao** [comment]
Will corresponding invoice/invoice lines be created for the adjustments?

**Comment by richardmoizeau** [comment]
> Do we need to consider permissions? Can anyone make stock adjustments or only certain users?

If we have existing permissions in OG that would be nice. But I suspect we only permissions for "invoices" right ?

**Comment by CarlosNZ** [comment]
> Will corresponding invoice/invoice lines be created for the adjustments? #2161

It is my understanding that all stocktakes and inventory adjustments result in an invoice/transaction being created (with lines obv).

**Comment by richardmoizeau** [comment]
> Another idea: Instead of quantity being editable, we have some kind of adjust button next to it, which opens another modal to do the inventory adjustment in.

This would be ideal. Maybe I got it wrong but @andreievg was suggesting to do it in a new tab ? Even potentially moving "repack" back into the modal as well. 

Let's also add and `OK and Next` button in this modal so you can quickly jump to the next record (stockline).

> Pretty sure we've been trying to avoid modal in modal

Big no no (right @anisha-msupply ? ;-) )

> STOCKTAKE: When starting a new stocktake, the modal should have an "Expired items" option (along with Master lists, etc). When this option is selected, the new stocktake is created with quantities defaulted to "0".

- I think we should make it similar to the existing filter on the OG's stocktake prompt (just `Expired Items` could be too limiting)

<img width="512" alt="Screenshot 2024-03-28 at 3 54 19 PM" src="https://github.com/msupply-foundation/open-msupply/assets/74992958/bb1a7020-96e6-4ad8-8057-7e5d7b8a5413">

- yes to the set to 0 action, set location would be another good one but would require a dropdown to select it so probably need design.

**Comment by andreievg** [comment]
## Expired through stocktake
* Add new stocktake 'filter' for expired (maybe with day offset from now)
* Mass reduce to 0 or location as action (will need modal)
* Actions on view stock page (idea for future)

### Quickly Add/Reduce stock for existing stock line (single)

* Reasons
* Enter adjustment as a difference rather (as well?) then new quantity

* New tab with adjustment (f/e mock api ?)
* Add history (f/e mock api?)
* Back end add adjustment
* Back end history 

### Add new stock line (single)

* Reasons
* Same UI as stock view modal (quantity editable)
* Search existing ? For duplicates ? And for prices matches
   * Auto complete on batch field
   * On loose focus on batch field ? Show warning with navigation to stock table with those filters applied

### Ledger

* Reconsider (just add inventory adjustments in the IA tab)

**Comment by lache-melvin** [comment]
Closing as initial IA work complete, carry over work is in #3755
