### ISSUE TITLE
GAPS: Additional requirements for registering CCE

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#3659]
## Background Information 

Epic #2896 introduced the CCEI management module. 

UNICEF Global have requested some additional functionality in order to address countries' pain points. 

The pain points are: 
-  There's no easy way for facilities to capture extensive details about their CCE

Problems to solve: 
- A way to easily capture cool / freezer rooms
- A way to capture all critical data for WHO PQS Catalogue CCE
- A way to capture all critical data for non-WHO PQS Catalogue CCE

## Describe the solution you'd like 🎁

**Documents**
- [User stories background](https://docs.google.com/document/d/1Sf7Sj6mCwHTZ0GtEW4O5eLJ9xi7FMHNKnWrHnf8Ueng/edit#heading=h.evuwlqiew02p) 

** Prerequisites **
- [x] #3868
- [x] #3971 -Refactor asset catalogue properties

- [x] #3930

** Should do ** 
- [ ] Edit screen for adding asset properties (in catalogue) - LOW PRIORITY

**User stories**
- [ ] A1.2 | A1.2.1 | A1.2.2
  - [x] #3867
  - [x] #3929
  - [x] #3866
  - [x] #3973
  - [ ] Register CCE by scanning a 2D DataMatrix

### Moneyworks Jobcode 🧰

CCEIDEV - development
CCEIDSN - design
CCEITEST - testing
CEEIDOC - documentation

**Comment by jmbrunskill** [comment]
### Testing Setup/Notes:
The docs talk about using a QR code to register/identify new assets, but that doesn't exist yet.

To test this, you'll need to create assets manually under `cold chain -> equipment`
![image](https://github.com/msupply-foundation/open-msupply/assets/8287373/854f5183-eed3-4b14-9553-7d4e0e54a95b)


Check that the described properties are in the list for each asset type (Fridges & Freezers, Cold/Freezer Rooms, Insulated Containers)

![image](https://github.com/msupply-foundation/open-msupply/assets/8287373/020f678e-8ac5-4b75-9f88-3ac923b650af)

- [ ] They should be editable if they are not defined in the catalogue.
- [ ] If the catalogue defines the property, it should not be editable.
- [ ] Properties should match this document for any thing defined by the asset catalogue - https://docs.google.com/spreadsheets/d/16VR8NE5VcQEY40J716zZ9mu6o-3aTwCTtbxVf-_sJy0/edit#gid=1945369047

**Comment by mark-prins** [comment]
Add the remaining issue to #4362

**Comment by marthakeezy** [comment]
Testing the rest when #4362 is closed, so moving this one to Done ✅
