### ISSUE TITLE
GAPS: Collecting data on the national cold storage infrastructure

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#3660]
## Background Information 

UNICEF Global have requested a tool to identify gaps in a country's cold storage infrastructure.  

The pain points are: 
-  There is no easy way for EPI managers to build up a picture of the infrastructure across the country. 

Problems to solve: 
- A way for central users to define the facility hierarchy 
- A way for facilities to send their data to a central repository
- A way for central users to be able to fill in / amend data collected from facilities as needed.

## Describe the solution you'd like 🎁
**Documents**
- [User stories background](https://docs.google.com/document/d/1Sf7Sj6mCwHTZ0GtEW4O5eLJ9xi7FMHNKnWrHnf8Ueng/edit#heading=h.evuwlqiew02p) 

**User stories**
- [ ] B.1.1
  - [x] Classify facilities by administrative level
- [ ] B.1.2
  - [x] Classify facilities by type
- [ ] B.1.3
  - [x] Classify facilities by ownership
- [ ] B.1.5 | B.1.5.1
  - [x] Collect energy infrastructure data from facilities
- [x] B.1.6 | B.1.6.1
  - [x] Collect CCE donor data from facilities

**Suggested approach**
Create store based custom fields for each of the properties required:
* ~Administrative~ Supply level ( perhaps this should be named category level? )
* Electricity
* Solar
* Kerosene
* Gas
* Facility type
* Facility ownership

e.g. 

<img width="832" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/0464df55-5c5c-4508-83d2-fb6a6f003bec">

These values can be defined at a central (mSupply central server) level
Sync these records from mSupply to open mSupply
- Create `custom_field` table
- Add sync translation to take custom field JSON (from prefs) and populate table
- Add `custom_data` column to the `name` table
- Add this to sync translation for the `name` table
Create UI to edit the store custom fields within open mSupply
- UI to display current fields
- API to fetch current data, and
- available fields
- API to save values
Sync locally edited values to mSupply
Create asset properties 
- add an entry for CCE Donor as this should be recorded at individual CCE level
Extend the customer & supplier import in mSupply to allow importing of custom data
Create a footrunner script to configure mSupply for the GAPS default data ( custom fields & ..? )
In open mSupply central add a page which lists names
- allows editing of custom field data for the names
In remote or central server (oms), you can edit the custom field information for the current store ( technically the name record of the current store)

**Notes**
Only the power and donor fields are listed as editable by the remote facility. Implementing the above would allow all fields to be editable and sync to open mSupply central server.

### Issues

* [x] #3862 
* [x] #3863 
* [x] #3865
* [x] #3864 
* [x] #3868
* [ ] Extend the customer & supplier import in mSupply to allow importing of custom data ([14702](https://github.com/msupply-foundation/msupply/issues/14702))
* [x] Create a footrunner script to configure mSupply for the GAPS default data ([14701](https://github.com/msupply-foundation/msupply/issues/14701))
* [x] #3905
* [x] #3906
* [x] #4085 
* [x] #4086 

### Moneyworks Jobcode 🧰

CCEIDEV - development
CCEIDSN - design
CCEITEST - testing
CEEIDOC - documentation

**Comment by mark-prins** [comment]
Thinking now to add donor as a link to a name record - showing a list of names which are donors and allowing selection. 
Still to be defined though, where the link is kept, extending sync to include donors, allowing singular links only or multiple, on central only?

**Comment by adamdewey** [comment]
> Thinking now to add donor as a link to a name record - showing a list of names which are donors and allowing selection. Still to be defined though, where the link is kept, extending sync to include donors, allowing singular links only or multiple, on central only?

Nice, so a name with type Donor?

I think it would be nice if we could allow multiple links per CCE if it's an easy win?
Otherwise a single link should be ok too.

**Comment by mark-prins** [comment]
cool - thanks @adamdewey.
Yep, a name with type Donor. It means defining them in mSupply atm, apart from that it feels like a neat solution.
We'll try for multiple donors per CCE then 🙏

**Comment by mark-prins** [comment]
Add the remaining issue to #4362
