### ISSUE TITLE
GAPS: Estimating cold storage capacity demand for current population

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#3662]
## Background Information 

UNICEF Global have requested a tool to identify gaps in a country's cold storage infrastructure.  

The pain points are: 
-  There is no easy way for EPI managers to estimate cold storage capacity demand for the country's population. 

Problems to solve: 
- A way for central users to be able to define the country's immunization programs
- A way for central users to collect demographic data from facilities
- A way to calculate the peak number of vaccines to be stored at each facility
- A way to calculate how much cold storage the vaccines occupy, in different packaging
- A way to calculate how much extra cold storage is needed for diluents
- A way to calculate the total cold storage needed per facility. 

## Success criteria
* [ ] Able to create demographic groups as a percentage of the population
* Able to create immunisation programs
  * [ ] Can create a new program
  * [ ] Can specify which demographic group it targets
  * [ ] Can specify a single vaccine
  * [ ] Can specify number of doses
  * [ ] Can specify coverage rate
  * [ ] Can specify wastage rate

## Describe the solution you'd like 🎁
**Documents**
- [User stories background](https://docs.google.com/document/d/1Sf7Sj6mCwHTZ0GtEW4O5eLJ9xi7FMHNKnWrHnf8Ueng/edit#heading=h.evuwlqiew02p) 

**User stories**
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-d3a2a440-7fff-2a6c-036c-7c223fe76397"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:10pt;"><span style="font-size:10pt;font-family:Montserrat,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">User Story B.2.2</span></p><div dir="ltr" style="margin-left:0pt;" align="left">
As a… | National EPI manager
-- | --
I want… | to be able to create demographic groups as a % of the total population
So that… | I have a simple way to numerically describe the different groups of people that are of interest to the central EPI office

</div></b>

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-6100dfc2-7fff-5c0e-727c-51a6ddc9feb4"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:10pt;"><span style="font-size:10pt;font-family:Montserrat,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">User Story B.2.1</span></p><div dir="ltr" style="margin-left:0pt;" align="left">
As a… | National EPI manager
-- | --
I want… | to be able to detail the key requirements of each individual immunization program
So that… | the cold storage demand for each immunization program can be tracked independently based on their unique set of requirements

</div></b>

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-73e6d88c-7fff-b746-5ebc-4fd2abb65825"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:10pt;"><span style="font-size:10pt;font-family:Montserrat,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">User Story B.2.1.1</span></p><div dir="ltr" style="margin-left:0pt;" align="left">
As a… | National EPI manager
-- | --
I want… | to be able to select which immunization programs should be included in demand calculations
So that… | I can easily run hypothetical gap analysis and compare what happens if I include a program or not in the calculations

</div></b>

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-31d90b6d-7fff-f334-72b1-8ac546860e29"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:10pt;"><span style="font-size:10pt;font-family:Montserrat,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">User Story B.2.3</span></p><div dir="ltr" style="margin-left:0pt;" align="left">
As a… | National EPI manager
-- | --
I want… | to be able to specify which demographic group each immunization program targets
So that… | our forecasting takes into account the number of people that require immunizing for each immunization program

</div></b>

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-856cbdf3-7fff-b08e-1094-fb938ba91975"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:10pt;"><span style="font-size:10pt;font-family:Montserrat,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">User Story B.2.4</span></p><div dir="ltr" style="margin-left:0pt;" align="left">
As a… | National EPI manager
-- | --
I want… | to be able to specify one or more vaccines which are required for each immunization program
So that… | our forecasting takes into account the type of vaccines involved for each immunization program

</div></b>

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-9e7495e7-7fff-0a18-113d-c8d6d1fb39f4"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:10pt;"><span style="font-size:10pt;font-family:Montserrat,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">User Story B.2.5</span></p><div dir="ltr" style="margin-left:0pt;" align="left">
As a… | National EPI manager
-- | --
I want… | to be able to specify how many doses of each vaccine is required to fully immunize a person in the target demographic
So that… | our forecasting takes into account the total number of doses required for each immunization program

</div></b>

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-826e8e70-7fff-4089-aace-28999e6e8a9a"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:10pt;"><span style="font-size:10pt;font-family:Montserrat,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">User Story B.2.6</span></p><div dir="ltr" style="margin-left:0pt;" align="left">
As a… | National EPI manager
-- | --
I want… | to be able to specify a 'coverage' percentage rate for each immunization program
So that… | I can easily apply a modifier to each immunization program to reflect real-world adjustments

</div></b>

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-df9bb5b7-7fff-ed72-23d6-19225200545a"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:10pt;"><span style="font-size:10pt;font-family:Montserrat,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">User Story B.2.10</span></p><div dir="ltr" style="margin-left:0pt;" align="left">
As a… | National EPI manager
-- | --
I want… | to be able to specify a 'wastage rate' for each type of vaccine
So that… | this modifier can be factored in when calculating the likely total quantity required to be cold stored for a given demographic

</div></b>

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-ad7db5e1-7fff-0f27-36d0-76f7bec06737"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:10pt;"><span style="font-size:10pt;font-family:Montserrat,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">User Story B.2.7.1</span></p><div dir="ltr" style="margin-left:0pt;" align="left">
As a… | National EPI manager
-- | --
I want… | to specify the cold storage volume requirements per dose for each type of vaccine per Primary, Secondary and Tertiary packaging
So that… | the volume calculation is accurate when different forms of packaging are used to store the vaccines

</div></b>

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-6ee65cae-7fff-470b-d216-fb8961fab19a"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:10pt;"><span style="font-size:10pt;font-family:Montserrat,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">User Story B.2.7.2</span></p><div dir="ltr" style="margin-left:0pt;" align="left">
As a… | National EPI manager
-- | --
I want… | the appropriate form of packaging (Primary, Secondary, Tertiary) used by each facility to be captured
So that… | the volume calculation is accurate for each facility

</div></b>

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-39c8fe9c-7fff-6f36-40c9-c11a5be8e555"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:10pt;"><span style="font-size:10pt;font-family:Montserrat,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">User Story B.2.8</span></p><div dir="ltr" style="margin-left:0pt;" align="left">
As a… | National EPI manager
-- | --
I want… | to specify the cold storage temperature requirements for each type of vaccine and also other products
So that… | the cold storage requirements can be broken down by temperature range

</div></b>

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-afa49a16-7fff-7992-825d-5506aff01de2"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:10pt;"><span style="font-size:10pt;font-family:Montserrat,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">User Story B.2.9</span></p><div dir="ltr" style="margin-left:0pt;" align="left">
As a… | National EPI manager
-- | --
I want… | to specify that each type of vaccine should be 'bundled' with diluents and / or syringes in certain ratios
So that… | any additional cold storage requirements can be taken into account if the diluents need to be stored cold too (and any additional dry storage requirements for syringes can be known too)

</div></b>

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-3843a7f3-7fff-751f-f02e-d4df40be2f27"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:10pt;"><span style="font-size:10pt;font-family:Montserrat,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">User Story B.2.12</span></p><div dir="ltr" style="margin-left:0pt;" align="left">
As a… | National EPI manager
-- | --
I want… | all facilities to indicate their expected annual supply interval (delivery schedule)
So that… | our forecasting can use this to calculate the maximum amount of each type of vaccine that can be expected to be stored at each facility at any point during the year

</div></b>

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-c4f17c68-7fff-0f97-5420-df2aa36369dd"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:10pt;"><span style="font-size:10pt;font-family:Montserrat,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">User Story B.2.13</span></p><div dir="ltr" style="margin-left:0pt;" align="left">
As a… | National EPI manager
-- | --
I want… | all facilities to indicate their expected stock safety buffer
So that… | our forecasting can use this to calculate the maximum amount of each type of vaccine that can be expected to be stored each facility at any point during the year

</div></b>

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-b2772ddf-7fff-323c-1e7e-a08c6433be75"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:10pt;"><span style="font-size:10pt;font-family:Montserrat,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">User Story B.2.14</span></p><div dir="ltr" style="margin-left:0pt;" align="left">
As a… | National EPI manager
-- | --
I want… | to be able to override any data that facilities populate
So that… | I can correct any missing or incorrect data if needed

</div></b>

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-f0478911-7fff-66ba-8b50-8cf51aa980a1"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:10pt;"><span style="font-size:10pt;font-family:Montserrat,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">User Story B.2.15</span></p><div dir="ltr" style="margin-left:0pt;" align="left">
As a… | National EPI manager
-- | --
I want… | to be able to enter data for facilities that are not using Open mSupply
So that… | we make sure all facilities are included in the calculations

</div></b>

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-eda2256a-7fff-8bd9-00f0-77aa1330fe69"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:10pt;"><span style="font-size:10pt;font-family:Montserrat,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">User Story B.2.16</span></p><div dir="ltr" style="margin-left:0pt;" align="left">
As a… | National EPI manager
-- | --
I want… | to be able to bulk upload data for facilities from Excel
So that… | I don't need to update each facility manually

</div></b>

**Issues**
- [x] #3844
- [x] #3848
- [x] #3921
- [x] #3922
- [x] #3911
- [x] #3913
- [x] #3915
- [x] #3916
- [ ] #3917 
- [ ] #3923
- [ ] [#14702](https://github.com/msupply-foundation/msupply/issues/14702)
- [x] [#14701](https://github.com/msupply-foundation/msupply/issues/14701)
- [x] Edit on behalf ( in #3905 & #3906 )

### Moneyworks Jobcode 🧰

CCEIDEV - CCEI Module Development
CCEIDSN - design
CCEITEST - testing
CEEIDOC - documentation

**Comment by jmbrunskill** [comment]
**Original UI Design**

![Image](https://github.com/msupply-foundation/open-msupply/assets/8287373/1fba9b1e-c194-4ece-8c84-4035e99445cb)

**Wireframe mockups**

Immunisation Program (List View)

![Image](https://github.com/msupply-foundation/open-msupply/assets/8287373/6ea02564-00e0-41ef-b100-557fd833c96d)

Immunisation (List View)

![Image](https://github.com/msupply-foundation/open-msupply/assets/8287373/1e466b70-8b6c-4275-abce-b82b2b876552)

Immunisation (DetailView)

![Image](https://github.com/msupply-foundation/open-msupply/assets/8287373/b949d961-24b3-4901-a0c0-219f44aa98e6)

**Comment by adamdewey** [comment]
Nice one @jmbrunskill!

Some observations: 

1. The immunization program list view and the immunization list view look quite similar to each other - might be a little confusing for the user - I wonder if there's a way we could make it more obvious they're nested / differentiate the screens more?
2. Unfortunately I don't think it will work to bundle items at the Immunization level - rather they need to be bundled at the Vaccine Item level as different items could require different bundles (e.g. different amount of diluent or different administration method)
3. We'll need a way to label each dose for the vaccination card (as well as number them)

**Comment by jmbrunskill** [comment]
> 2\. Unfortunately I don't think it will work to bundle items at the Immunization level - rather they need to be bundled at the Vaccine Item level as different items could require different bundles (e.g. different amount of diluent or different administration method)

Are you implying more than one vaccine type in an Immunisation?
From you design it looks like if you wanted to administer Hep B and OPV both to `new borns` you'd need to create two immunisations under the `Routine Immunisations for Children`

I understand that alternative manufacturers might have different mechanisms & bundled items I guess.

What if we create a different Immunisation for each vaccine variant?

Something like this...


![Image](https://github.com/msupply-foundation/open-msupply/assets/8287373/27f3a591-e922-4990-bd7e-25ac0917e01b)



![Image](https://github.com/msupply-foundation/open-msupply/assets/8287373/c42742b0-aa8b-4055-9545-5124621f7d29)

Then we'd have a method to control how much of each vaccine you're planning to use with the Coverage Rate?

**Comment by adamdewey** [comment]
> From you design it looks like if you wanted to administer Hep B and OPV both to new borns you'd need to create two immunisations under the Routine Immunisations for Children is that your understanding too?

Yes that's correct. 

> What if we create a different Immunisation for each vaccine variant?

This would be ok from the GAPS pov.

The problem here is how to track things at the vaccination card level.

The vaccination card needs to track whether a patient has received sufficient doses for a particular disease or combination of diseases (e.g. MMR).

But the tracking is likely to be variant agnostic. 

So we need a way to say "these variants are all equivalent in the eyes of the vaccination card"

**Comment by jmbrunskill** [comment]
Ok will keep working on options then. Definitely complicates things!

**Comment by adamdewey** [comment]
@jmbrunskill Yeah it is a bit complicated - even the concepts are quite difficult and not nice and clean! 

E.g. some immunizations just address 1 disease and others address multiple. 

And some combinations change - e.g. Hep A could be given on its own or it could be given together with Typhoid. 

Hmm, actually that's made me think a bit more...

Let's have a chat about this tomorrow in the office? 

I think we need to get our heads around it to design something that isn't going to paint us into a corner...

**Comment by mark-prins** [comment]
Add the remaining issues to #4362
