### ISSUE TITLE
GAPS: Identifying CCE that will need replacing within the next 5 years

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#3697]
## Background Information 

UNICEF Global have requested a tool to identify gaps in a country's cold storage infrastructure.  

The pain points are: 
-  There is no easy way for EPI managers to identify how many CCE will need replacing in the near term and which facilities will be affected.

Problems to solve: 
- A way for central users to be able to define the nationally accepted lifespan for each type of CCE model
- A way to calculate which of the country's CCE are due to pass their accepted lifespan in the next 5 years. 
- A way for facilities to report on permanently broken CCE so that these can be included in replacement calculations too. 

## Acceptance criteria
* [ ] Able to define the lifespan of catalogue items
* [ ] Can set the lifespan when importing catalogue items
* [ ] Can set the status of an asset as `Unserviceable`

## Describe the solution you'd like 🎁
**Documents**
- [User stories background](https://docs.google.com/document/d/1Sf7Sj6mCwHTZ0GtEW4O5eLJ9xi7FMHNKnWrHnf8Ueng/edit#heading=h.evuwlqiew02p) 

**User stories**

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-9ab71f67-7fff-194a-7482-0a9258312e49"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:10pt;"><span style="font-size:10pt;font-family:Montserrat,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">User Story B.4.1</span></p><div dir="ltr" style="margin-left:0pt;" align="left">
As a… | National EPI manager
-- | --
I want… | to know the cold storage capacity that will be need to be replaced over the next 5 years
So that… | I have an idea of how much CCE will need to be replaced and can plan accordingly

</div></b>

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-d279ea06-7fff-cd7f-ccae-a637af42bfbe"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:10pt;"><span style="font-size:10pt;font-family:Montserrat,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">User Story B.4.2</span></p><div dir="ltr" style="margin-left:0pt;" align="left">
As a… | National EPI manager
-- | --
I want… | to specify the nationally agreed expected lifespan for each type of CCE
So that… | the system can tell me when any CCE in the country are approaching the end of this lifespan and can request replacements for these in our next CCEOP application

</div></b>

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-d1e8bfc3-7fff-02ea-0000-7db279a72c2c"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:Montserrat,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">User Story B.4.3</span></p><div dir="ltr" style="margin-left:0pt;" align="left">
As a… | National EPI manager
-- | --
I want… | all facilities to provide me with information about any CCE that are unserviceable (permanently broken)
So that… | we request replacements for these in our next CCEOP application

</div></b>

## Issues
* [ ] #3908
* [x] #3907

### Moneyworks Jobcode 🧰

CCEIDEV - development
CCEIDSN - design
CCEITEST - testing
CEEIDOC - documentation

**Comment by mark-prins** [comment]
Add the remaining issue to #4362

**Comment by marthakeezy** [comment]
Testing the rest when #4362 is closed, so moving this one to Done ✅
