### ISSUE TITLE
Migration Pathways between Open mSupply -> Mobile/Desktop : v2.0.0 Release Testing

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3699]
# Migrate from desktop to oms
## Setting up some data in desktop-OG first
- [x] Setup a remote desktop site syncing with at least v7-14-00 mSupply Cloud
- [x] Create some locations
- [x] Create some barcodes 
- [x] Create some transactions like invoices, requisitions and returns in both `nw` & `fn` status
    - [x] Make transactions from desktop to desktop
    - [x] Also make transactions from desktop to oms and vice versa
- [x] Also create some repacks and stocktakes
- [x] Create some patient names and prescriptions
- [x] Create some users with some store-permissions

### Extra currency-setup for desktop
- [x] Introduce multiple currencies
- [x] Create some transactions with different currencies
- [x] Also delete one of the currencies and note it (for later)

### Extra setup to cover #2760 
- [x] Create a facility-name1 and issue some stocks to that facility-name1 from your logged-in remote-store2.
- [x] Have all statuses of CI: `sg`, `cn` & `fn` on one date
- [ ] On next date(make it gap of at least 3 months), create store1 from that very facility-name1
- [x] Initialise that new store1 and you'll see the corresponding SI's made as well
- [x] From current supplying remote-store2, check there are previous `sg` or `cn` CI's 

## Migrate desktop-OG to oms
- [x] In mSupply Cloud, reset hardware ID and application-mode (App name & App version) in that remote-site window
- [x] Reinitialise that site, this time from oms v2.0.0
- [ ] Make sure the previously-set user-permissions are working fine: minor-problems: [comment1](https://github.com/msupply-foundation/open-msupply/issues/3699#issuecomment-2088093451)
- [x] Make sure the locations appear fine
- [x] Make sure the barcodes appear fine 
- [x] Check the previously made transactions
- [ ] All the `fn` transactions should be fine  
    - [x] Previous CI's should appear under Outbound Shipments
    - [x] Previous SI's should appear under Inbound Shipments
    - [x] Previous SC's should appear under Outbound Returns 
    - [x] Previous CC's should appear under Inbound Returns 
    - [x] Previous IO's should appear under Internal Orders
    - [x] Previous customer requisition should appear under Requisitions
    - [ ] Previous repacks and  stocktakes should also appear correctly: some problems: [comment2-point1&2](https://github.com/msupply-foundation/open-msupply/issues/3699#issuecomment-2088186569)
    - [x] Previous patient-names and prescriptions should also appear correctly
- [ ] Also check the `nw` or `sg` transactions
    - [ ] Try to process the `nw` CI; go ahead and finalise it
         - [x] CI should get finalised
         - [ ] After proper sync, corresponding SI should be created in receiving-store : seeing some problems here: [comment2-point3](https://github.com/msupply-foundation/open-msupply/issues/3699#issuecomment-2088186569)
    - [x] Try to process the `nw` IO; go ahead and finalise it
         - [x] IO should get finalised
         - [x] After proper sync, corresponding customer-requisition should be created in receiving-store
    - [ ] Try to process the `cn` SC; go ahead and finalise it
         - [ ] SC/Outbound-Return should get finalised/shipped
         - [ ] After proper sync, corresponding Inbound-Return should be created in receiving-store
- [ ] Make sure no lines are missing from transactions - I notice lines missing from stocktakes
- [x] Make sure the transaction statuses are also fine - bearable I'd say
- [ ] Make sure the names, comments, reference, etc fields are populated correctly - #3738

### Extra currency migrations test
- [x] Make sure the previous transactions created in different currencies reflect accordingly in oms
- [x] Prevoiusly deleted currency should not show up in oms
   
### Extra tests to cover #2760 
- [x] In store2, Check that previous `sg` or `cn` outbound shipment and try to issue them
    - [ ] You should not be able to proceed with those lines? : Issues: [mSupply-#14663](https://github.com/msupply-foundation/msupply/issues/14663), [#3734](https://github.com/msupply-foundation/open-msupply/issues/3734)
- [x] In store1, check the previous SI and try to finalise it
    - [ ] You should not be able to proceed with those lines? - It gets on Hold by default, which I think is okay; will confirm in a while

# Migrate from mobile to oms
## Setting up some data in mobile-OG first
- [x] Setup a remote mobile site syncing with at least v7-14-00 mSupply Cloud
- [x] Create some transactions like invoices and requisitions in both `nw` & `fn` status
    - [x] Make transactions from mobile to desktop
    - [x] Also make transactions from mobile to oms and vice versa
- [x] Also create some stocktakes
- [x] Create some patient names and prescriptions

## Migrate mobile to oms
- [x] In mSupply Cloud, reset hardware ID and application-mode (App name & App version) in that remote-site window
- [x] Reinitialise that site, this time from oms v2.0.0
- [x] Make sure the previously-set user-permissions are working fine
- [x] Check the previously made transactions
- [x] All the `fn` transactions should be fine  
    - [x] Previous CI's should appear under Outbound Shipments
    - [x] Previous SI's should appear under Inbound Shipments
    - [x] Previous customer requisition should appear under Requisitions
    - [ ] Previous  stocktakes should also appear correctly **-same problem as above**
    - [x] Previous patient-names and prescriptions should also appear correctly
- [x] Also check the `nw` or `sg` transactions
    - [x] Try to process the `nw` CI; go ahead and finalise it
         - [x] CI should get finalised
         - [x] After proper sync, corresponding SI should be created in receiving-store
    - [x] Try to process the `nw` IO; go ahead and finalise it
         - [x] IO should get finalised
         - [x] After proper sync, corresponding customer-requisition should be created in receiving-store
    - [ ] Try to process the `nw` stocktake; go ahead and finalise it **-same problem as above**
         - [ ] Stocktake should get finalised and there should be added stocks in the store afterwards
- [ ] Make sure no lines are missing from transactions **-same problem as above**
- [x] Make sure the transaction statuses are also fine
- [ ] Make sure the names. comments, reference, etc fields are populated correctly **- FAILED** : #3738

**Comment by roxy-dao** [comment]
Just reiterating from meeting: 

For https://github.com/msupply-foundation/open-msupply/issues/2760, the invoices have to be older than store creation date by 3 months. So would probably need some data manipulation, can you do that through record browser? 

The rest of the tests sound good to me!

**Comment by nisha-dangol** [comment]
> Just reiterating from meeting:
> 
> For #2760, the invoices have to be older than store creation date by 3 months. So would probably need some data manipulation, can you do that through record browser? Or change the time on your device (;
> 
> The rest of the tests sound good to me!

yup, can do.

**Comment by nisha-dangol** [comment]
Just noticed that; users created from remote-desktop site after migrating to oms, now those users won't show up; which is technically correct because those users by default are Inactive on mSupply cloud and users in oms are syncing currently to Cloud
Is there anything that can be done about this for smooth transition from desktop to oms or we discard this and warn people to ensure/configure the users first in mSupply Cloud before converting to oms? @roxy-dao @Chris-Petty

**Comment by nisha-dangol** [comment]
Further observations:
1. Repacks created from desktop (left in `sg` status), after converted to oms-store; now can't be processed at all. They do show up in history, but looks like no way to proceed. Should there be new issue to address this? or we can just leave it?
2. Stocktake finalised in desktop, after converted to oms-store shows no items entry at all. I'm guessing this is an open issue for mSupply v7.14.XX : #https://github.com/msupply-foundation/msupply/issues/14624 , but I can be wrong as well. Good to confirm @roxy-dao and we can submit another issue if needed?

**Comment by roxy-dao** [comment]
1. Please create an issue to address this.
2. Yeah, unfortunately have to wait until that issue is merged in OG for stocktake lines to merge again. I'll check with @JonnaQuismundo is it is still going in a patch.
3. The 2023-12-12 shouldn't have a corresponding IS 🤔

**Comment by Chris-Petty** [comment]
2. Yes it is going in patch, I will review today
3. I must be misunderstanding, you mostly emphasise that the new SI exists for the old CI that you _recently_ finalised, which is expected? Which SI is missing? 

I see how you're doing the migration and that is _very_ unconventional and definitely not how migration will be done in production so I'm worried about validity of tests there. You should wipe the datafile on OMS and reinitialise generally, though that is a bit of a chore 😕.

**Comment by nisha-dangol** [comment]
> 3. I must be misunderstanding, you mostly emphasise that the new SI exists for the old CI that you _recently_ finalised, which is expected? Which SI is missing?
> 
@Chris-Petty here's the breakdown of the steps for Scenarior 3:
- create a store on 2022-12-12
- create a CI (of ‘nw’ status, and note it has to be a stock-transfer, i.e., create CI to another store) on desktop-remote-site on 2023-12-12 and sync completely
- move that remote-site to oms v2.0 by completely clearing the hardware ID & all, then re-initialise on oms on today’s date: 2024-05-02
- now in oms, check that previously created CI of 'nw/sg' status
- finalise it (In oms language, change status to Shipped) and sync
- for the receiving-store, the corresponding SI is not created at all - this SI is the one missing.

**Comment by nisha-dangol** [comment]
> 1. Please create an issue to address this.
> 2. Yeah, unfortunately have to wait until that issue is merged in OG for stocktake lines to merge again. I'll check with @JonnaQuismundo if it is still going in a patch.
> 3. The 2023-12-12 shouldn't have a corresponding IS 🤔

@Chris-Petty @roxy-dao 
1. Submitted issue: #3733
2. Will wait for v7.14.XX and re-try again after I get that installer
3. For now, I've submitted #3734 with details, we can discuss and decide to proceed or discard accordingly

**Comment by nisha-dangol** [comment]
While testing mobile-oms migrations, at one point, I ended up migrating back from oms to mobile, which I know is very unlikely to happen at all; but here's one interesting issue:
- created prescriptions in mobile and synced
- converted it to oms and synced
- converted it back to mobile again and synced
- that prescription now appears under 'Customer Invoices'

**Comment by Chris-Petty** [comment]
> > 3. I must be misunderstanding, you mostly emphasise that the new SI exists for the old CI that you _recently_ finalised, which is expected? Which SI is missing?
> 
> @Chris-Petty here's the breakdown of the steps for Scenario 3:
> 
>     * create a store on 2022-12-12
> 
>     * create a CI (of ‘nw’ status, and note it has to be a stock-transfer, i.e., create CI to another store) on desktop-remote-siteA on 2023-12-12 and sync completely
> 
>     * move that remote-siteA to oms v2.0 by completely clearing the hardware ID & all, then re-initialise on oms on today’s date: 2024-05-02
> 
>     * now in oms-siteA, check that previously created CI of 'nw/sg' status
> 
>     * finalise it (In oms language, change status to Shipped) and sync
> 
>     * for the receiving-storeB, the corresponding SI is not created at all - this SI is the one missing.

Is the receiving-storeB also OMS?

For reference the OMS code that should affect this:
https://github.com/msupply-foundation/open-msupply/blob/02a6af05cfe4b216f5747f972303eff68bbe6407/server/service/src/processors/transfer/shipment/create_inbound_shipment.rs#L89-L99

If storeB is on OMS it is seeing is an invoice made on 2023-12-12, and storeB was created on ????. If storeB.created_date is >2024-01-12 then it will not make the SI (and the central server won't have it either).

**Comment by nisha-dangol** [comment]
> > @Chris-Petty here's the breakdown of the steps for Scenario 3:
> > ```
> > * create a store on 2022-12-12
> > 
> > * create a CI (of ‘nw’ status, and note it has to be a stock-transfer, i.e., create CI to another store) on desktop-remote-siteA on 2023-12-12 and sync completely
> > 
> > * move that remote-siteA to oms v2.0 by completely clearing the hardware ID & all, then re-initialise on oms on today’s date: 2024-05-02
> > 
> > * now in oms-siteA, check that previously created CI of 'nw/sg' status
> > 
> > * finalise it (In oms language, change status to Shipped) and sync
> > 
> > * for the receiving-storeB, the corresponding SI is not created at all - this SI is the one missing.
> > ```
> 
> Is the receiving-storeB also OMS?
> 
Yes, it is.
<br><br>


> If storeB is on OMS it is seeing is an invoice made on 2023-12-12, and storeB was created on ????. If storeB.created_date is >2024-01-12 then it will not make the SI (and the central server won't have it either).
>
storeB was created way before 2024, somewhere around 2023-07-xx. FYI, I've submitted the details in another issue already regrading this: #3734

**Comment by nisha-dangol** [comment]
Moving this to Done, since I see further related issues will be addressed in v2.1.0
