### ISSUE TITLE
Feature: Basic Reports

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#3880]
# Basic Reports

[Spec Document](https://docs.google.com/document/d/1jwRw2fMfst2OyIbULIlCPJF4yH554XuR5qkANKHQPgw/edit)

### Tasks

- [x] https://github.com/msupply-foundation/open-msupply/issues/3882
- [ ] Improve report generation and configuration
    * One JSON file rather then multiple when uploading to mSupply ?
    * https://github.com/msupply-foundation/open-msupply/issues/4430
    * https://github.com/msupply-foundation/open-msupply-reports/pull/70
- [x] #4401
    * How to categorise them ? Maybe leave categorisation till later
- [x] https://github.com/msupply-foundation/open-msupply/issues/4419
- [x] https://github.com/msupply-foundation/open-msupply/issues/4420
- [x] #4441 Calculate AMC using store preference look back period
- [ ] Can export report, as excel https://github.com/msupply-foundation/open-msupply/issues/2868
- [ ] Reports are either backwards compatible or there is a mechanism to keep them tested/updated https://github.com/msupply-foundation/open-msupply/issues/2000
   * How do we know that latest report are available for customer ?
- [x] #4443
- [x] #4447
- [x] #4448
- [x] #4450
- [x] #4444
- [x] #4451
- [x] #4459
- [x] Filter reports in report menu
- [ ] Update sample report in report repo ?
- [x] #4501
- [ ] Monthly consumption look back period should now show as 0 in report argument view
     * For this one I would overwrite in repository as per: https://github.com/msupply-foundation/open-msupply/compare/expiring-item-report...expiring-item-report(Default-amc-look-back-months)
- [x] #4464

### Summary

An area in omSupply for reports:

* List available reports
* Generate report with specified
* View generated report (html)
* Print generated report (pdf/html)
* Export/Download generated report (pdf, excel)
* All reports are configurable (query to get data, sql and graphql + display of this data with zola templating)
* omSupply comes with some standard reports, standard report can be customised and new report can be added via configurations

### Additional context 💌

How we use report already ?

Export to excel ?

How do we keep report working (backwards compatibility) ?

Extra tools to speed up report display (like seeing to arguments etc..)

<details>
<summary>
Meeting 25-06
</summary>

> Should still have custom 'branding' on reports, which means the 'data' part of the report should be identified, so it can be displayed as a table in omSupply.
> 
> Filter detail view is designs is a swipe detail view on the right, this for v1 could just be normal details view (like shipments etc)
> 
> There needs to be a button on filters to apply filter (generate report). Starting point for a report could be blank page with just the filter detail view.
> 
> Need to also export to excel, though we could just export data to csv, but would require a mapping between html result and something, it's probably good to make this something a starting point for future extensions (thus to use some excel library rather then csv), although would also be good to check how excel xml is structure and if there is more direct mapping between html and xml
> 
> Preference button from report view would show the configurations from this issue: https://github.com/msupply-foundation/open-msupply/issues/3882
> 
> Program reports to be consolidated into the same report page
> 
> Should display the table of data before printing, for now just render output html (the data bit of it), no pagenation
> 
> Reports page should have some filter at some stage (cause could have a lot of reports)
> 
> Can get styles from Figma 

</details>

Permissions ?

### Tests

We will try to write full set of tests and setup instructions in this epic. As we submit PRs the test will be updated here and referenced in the PR. This will allow QA team to build test templates by referencing one set of test instructions

1. The following store preferences sync correctly and are displayed in the Detail Panel of the Reports ListView page:

![Screenshot 2024-07-12 at 4 53 14 PM](https://github.com/user-attachments/assets/8726418b-c49e-4719-9087-accbd21b9622)

![Screenshot 2024-07-29 at 9 29 35 AM](https://github.com/user-attachments/assets/4b0a39f4-0026-4d75-9cda-39507e866c0c)

2. When omSupply is migrated from version < 2.2, store preference should be updated to include values configured in mSupply (configure in mSupply before upgrade, sync store preference changes before upgrade, these preferences should be shows after upgrade to omSupply)

3. Download reports from report repository, upload them to OG with subcontext: StockAndItems or Expiring. Sync. The reports should now show up on the report page.
4. Click on one of the reports on the report page and ensure that it shows the correct report
5. Try using the filters (Note: There is a bug if you type to fast when filtering, will be looked at)
6. For item usage, generate report base analysis on whatever months you have your lookback_months set to
7. Check the print button is working
8. Check the export button downloads and opens in excel

### Moneyworks Jobcode 🧰

OMS:REPT

## Report Menu
![Screenshot 2024-07-08 at 5 31 27 PM](https://github.com/msupply-foundation/open-msupply/assets/26194949/091545de-95fd-4332-8fed-b31b42494e08)

**Comment by andreievg** [comment]
https://github.com/msupply-foundation/msupply/issues/14465

**Comment by andreievg** [comment]
We had issue with Pagination in graphql in reports config, should spend some time thinking about how to make report more resilient to paginations in the future

**Comment by roxy-dao** [comment]
Carry over in #4668

**Comment by marthakeezy** [comment]
Basic Reports were tested in V2.3.0 Release testing, so moving to Done since there is a new issue linked above for carryover issues ✅
