### ISSUE TITLE
Clarify sync page messaging

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4006]
## Is your feature request related to a problem? Please describe 👀
There has been some changes requested of the sync status page.

Would like to see:
- When did it last attempt to sync
- When did it last succeed

And "I don't find the User configuration last updated useful - I don't even understand what that does really"

## Describe the solution you'd like 🎁
* Always show the `Last successful sync` message
* Change the last sync value to be the finished datetime, with a `-` if not complete (alternative? a 'not completed' message?) and update the wording to include 'finished' or 'completed'
* Remove `User configuration last updated` ( now that this is part of the standard sync process, it will happen at the same time! )

<img width="583" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/6a2ad541-67b2-44aa-af77-93baf81d486e">

Perhaps also a traffic light red/green indicator that all is ok?

### Describe alternatives you've considered 💭
We can keep as is, and use training. Would prefer to have an easily understandable UI though.

## Tasks

<img alt="image" width="558" src="https://private-user-images.githubusercontent.com/9192912/333928550-b6431697-4ee1-4225-b93d-0bc260068095.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwMzI1ODMsIm5iZiI6MTcxNzAzMjI4MywicGF0aCI6Ii85MTkyOTEyLzMzMzkyODU1MC1iNjQzMTY5Ny00ZWUxLTQyMjUtYjkzZC0wYmMyNjAwNjgwOTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MzBUMDEyNDQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjllZTk4NTU1YWUyM2JkNDM3YWFiNmU3OGIzYmQ3YjRlNjIwYTg5MjFmNGU1MTY5ZmRmMmIwYWNhZjE0N2FlNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HCueuaJ2OsutCO89yIgcdPmnf6eJ6boeaWcbMpT_MLM">

Refinement: Show everything like in this screenshot

- [ ] Always show "last successful sync finished"
- [ ] Track duration of sync in the sync process
- [ ] Add duration to the sync stats record in database
- [ ] Expose in GQL
- [ ] Render new duration element in sync status page

**Comment by adamdewey** [comment]
Looks great!

To be a pedant, perhaps wording could be `Last successful sync completed` ?

**Comment by mark-prins** [comment]
Yes, thanks - I like 'completed'

Bonus thought: we have start and finish times. what about adding duration in?

<img width="558" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/b6431697-4ee1-4225-b93d-0bc260068095">

**Comment by adamdewey** [comment]
Oo fancy!

Hmm, unsure how useful it would be to the end user, but not sure it would hurt either?

Could be useful for support for troubleshooting perhaps??

**Comment by Gwalior-84** [comment]
> Oo fancy!
> 
> Hmm, unsure how useful it would be to the end user, but not sure it would hurt either?
> 
> Could be useful for support for troubleshooting perhaps??

Yes, the more information on a support screenshot, the better!

**Comment by roxy-dao** [comment]
> Yes, thanks - I like 'completed'
> 
> Bonus thought: we have start and finish times. what about adding duration in?
> 
> <img alt="image" width="558" src="https://private-user-images.githubusercontent.com/9192912/333928550-b6431697-4ee1-4225-b93d-0bc260068095.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwMzI1ODMsIm5iZiI6MTcxNzAzMjI4MywicGF0aCI6Ii85MTkyOTEyLzMzMzkyODU1MC1iNjQzMTY5Ny00ZWUxLTQyMjUtYjkzZC0wYmMyNjAwNjgwOTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MzBUMDEyNDQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjllZTk4NTU1YWUyM2JkNDM3YWFiNmU3OGIzYmQ3YjRlNjIwYTg5MjFmNGU1MTY5ZmRmMmIwYWNhZjE0N2FlNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HCueuaJ2OsutCO89yIgcdPmnf6eJ6boeaWcbMpT_MLM">

Refinement: Show everything like in this screenshot
1. Add duration into the table
2. Calculate
3. And expose in API

**Comment by mark-prins** [comment]
not broken and not high priority.. however, would be great to have and it's a quick win. putting in v2.2 even though it's a 'delightful'

**Comment by regotaina** [comment]
Tested on RC5

Desktop app

# 🧪 Testing



- [ ] test the migrations with postgres and sqlite
- [ ] check that the duration column is populated
- [ ] check that the display looks ok
