### ISSUE TITLE
Testing: Inventory Adjustments

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#4036]
## Details 🤔

This issue was developed with the intention of testing whether all parts of the feature is typically functioning according to docs . 
Documentation: [oms Inventory Adjustments
](https://docs-staging.msupply.foundation/docs/inventory/stock-view/#creating-a-new-stock-line)

## Your environment 🌱

- Version:` 2.1.0-IA-test`
- mSupply version: V7.15
- Platform:
   - [x] android (tablet)
   - [ ] browser (remote login)
   - [x] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)
   
#  Inventory Adjustments Issues

## Quickly Add/Reduce stock for existing stock line

- [x] #3496
- [x] #3497
- [x] #3498
- [x] #3499
- [x] #3656 

## Add new stock line 

- [x] #3500
- [x] #3501

## Stocktakes - new filter and bulk actions
- [x] #3502 
- [x] #3503

## Extra

- [x] #3604 - no need to test, this was just for 2.0, removed for 2.1. Just flagging here!

**Comment by regotaina** [comment]
Testing inventory adjustments view modal 

# 🧪 How has/should this change been tested? 


- [ ] Select an adjustment direction
- [ ] Other fields should enable
- [ ] Enter a reason
- [ ] Update `adjust by` - `new number of packs` should update accordingly
- [ ] Update `new number of packs` - `adjust by` should update accordingly
- [ ] You get a success snack and the form is reset on save

**Comment by regotaina** [comment]
Testing Ledger tab

# 🧪 How has/should this change been tested?

**Comment by regotaina** [comment]
It's looking good so far! 👍🏾 

ledger after positive/negative inventory adjustments
![Screenshot 2024-06-05 at 2 01 22 PM](https://github.com/msupply-foundation/open-msupply/assets/132425096/4a8e1f4d-7eeb-4afb-8588-a81b359c5023)

**Comment by regotaina** [comment]
Testing new filter #3648 

# 🧪 Testing

- [ ] Create a new stocktake and filter by expiry date. 
- [ ] Check the resulting stock list in new stocktake is correct - the expiry date before selected date

**Comment by regotaina** [comment]
Testing move stock line to it's own page #3961 

# 🧪 Testing

- [ ] Can click on a stock line in "View Stock" list and load the correct page
- [ ] Can click "New Stock" from list page and add a new stock line
- [ ] Can edit stock details on page, with "Cancel" and "Save" functionality behaving as expected
- [ ] Log and Ledger tabs display correct and function as before

**Comment by regotaina** [comment]
> It's looking good so far! 👍🏾 I'm not sure why the date is recorded as MMDDYYYY instead of DDMMYYYY.
> 
> this screenshot is on the app, it's not following my computer as it looks DDMMYYYY on the main settings.
> 
> ledger after positive/negative inventory adjustments ![Screenshot 2024-06-05 at 2 01 22 PM](https://private-user-images.githubusercontent.com/132425096/336659869-4a8e1f4d-7eeb-4afb-8588-a81b359c5023.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NTQ3MTMsIm5iZiI6MTcxNzU1NDQxMywicGF0aCI6Ii8xMzI0MjUwOTYvMzM2NjU5ODY5LTRhOGUxZjRkLTdlZWItNGFmYi04NTg4LWE4MWIzNTljNTAyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNVQwMjI2NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZmRiOWY1OWJkZTEyN2UyY2MzN2RhNmM4YmVhOTc1OWE1MjM3M2M5ZDA2MzU0MGQ4YzI3ZGFmZWQxZjg1ZmY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.i9Yj30riWHL72Rpq4XdMLrxHtYoSfs3f9trwyznln5I)

@lache-melvin  discovered that OMS will follow the date format of the browser!

**Comment by regotaina** [comment]
# 🧪 How has/should this change been tested? 


- Create a stocktake
- Add some lines
- Select some lines
- Select action "reduce lines to 0"
- [ ] Modal appears - if reasons configured, you have to enter a reason
- [ ] Ok button enables - click ok
- [ ] Selected placeholder lines (blue) are now included lines (black), the counted # packs is 0, and your reason should be applied to all of the selected lines
- Select some lines
- Select action "change location of lines"
- [ ] Modal appears - select a new location

**Comment by regotaina** [comment]
# 🧪 Testing



- [ ] Navigate to stock view
- [ ] Click the `New Stock` button (if it's not there, ensure you have the Inventory Adjustments feature enabled)
- [ ] Select an item and fill in the form, including an inventory adjustment reason
- [ ] Click Ok
- [ ] You should now be able to find your new stock line in the stock list

**Comment by regotaina** [comment]
All tested on Desktop app. Green flags  🥇 

I will complete the tests on .apk

**Comment by regotaina** [comment]
Tested on .apk

Works as expected. Got a weird bug once with 'Reason' not being enabled, when clearly there were reasons synced before. @lache-melvin was there, can attest I wasn't dellusional.

I cannot reproduce it anymore, so will keep an eye for it.
