### ISSUE TITLE
GAPS: Phase two

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4362]
## Background Information 

UNICEF Global have requested a tool to identify gaps in a country's cold storage infrastructure.
The work has been split into two phases across 4 epics.
There's a few leftover issues and to consolidate functionality and make testing clearer, this epic wraps up the loose ends.

## Acceptance criteria

- [x] Can create item variants and assign properties
- [x] Can specify item variant bundles
- [x] See activity logging for demographics actions
- [x] Assign internal locations on CC Asset to Temperature ranges

## User stories

- A.1.2 | A.1.2.1 | A.1.2.2 (from epic #3659)
  - [x] #4757
- From epic #3660
  - [x] Create a footrunner script to configure mSupply for the GAPS default data (https://github.com/msupply-foundation/msupply/issues/14702)
- A.6.2
  - [x] #4367 
- B.2.7.1 | B.2.8 | B.2.9 (From epic #3662)
  - [x] #4789
  - [x] #5141
  - [x] #5145
  - [x] #3917
  - [x] #3923
  - [x] #4368 
- [ ] B.2.13 (from #3663)
  - [x] #4370 
- B.4.1 | B.4.2 (from epic #3697)
  - [x] #3908
- Misc functionality ( not capture by user stories )
  - [x] #4343
  - [x] #5100
 

### Moneyworks Jobcode 🧰

CCEIDEV - development
CCEIDSN - design
CCEITEST - testing
CEEIDOC - documentation

#### Setup

- Ensure your store has `Uses Vaccine Module` store preference enabled
- Your user will need the `omSupply -> Manage central data` user permission for the central store
- Configure some location types in mSupply (Menu Bar, Item -> Show location types...)

#### Steps

Please add to these as you see more use cases!

- Cold storage types
  - [ ] Sync & ensure that under Inventory -> Locations, when editing a location, you can add a storage type - the options are the same options you configured as location types in mSupply
    - [ ] Selected storage type/temperature range should show in list view
    - [ ] In the Inbound Shipment edit modal, the Customer Return edit modal, and the View Stock -> Detail view, the locations picker should now include the cold storage type name in brackets
    - [ ] In Coldchain -> Equipment, looking at an asset that belongs to your store, you should be able to assign the asset to a location. The storage type should show in that location picker
- [Item Variants](https://docs-staging.msupply.foundation/docs/catalogue/items/#item-variants)
  - [ ] Before configuring any item variants, ensure the Inbound Shipment edit modal, the Customer Return edit modal, and the View Stock -> Detail view do NOT have an Item Variant input column/field
  - [ ] On OMS Central server, under item detail view, you can see a new tab `Variants`
    - [ ] When on the `Variants` tab, an `Add Variant` button appears in the app header
    - [ ] Clicking this button opens a modal
    - [ ] You can't save until you define a name
    - [ ] The `Temperature` options are the location types from mSupply
    - [ ] The `Manufacturers` are configured from mSupply (names marked as Manufacturer)
    - [ ] Saving adds the new variant
    - [ ] All the entered information is visible in the `Variants` tab
    - [ ] Clicking the `Edit` button reopens the modal and you can make changes
    - [ ] Clicking the delete button gives a confirmation modal, then deletes the variant
    - [ ] Have variants configured for at least 2 different items
    - [ ] Under a variant, click the add bundled item button
    - [ ] You cannot select the item you are already editing (i.e. you cannot bundle 2 variants of the same item)
    - [ ] Select a variant of the other item
    - [ ] Define a ratio
    - [ ] Save - a row has been added to the bundled items table
    - [ ] Click the row to edit
    - [ ] The delete button shows a confirmation, then deletes the bundled item
    - [ ] After adding a bundled item, ensure you can't bundle the same variant twice
    - [ ] When viewing the other variant, the inverse of the ratio is shown
    - [ ] You cannot bundle items onto the other variant (nested bundling not allowed)
    - [ ] Item variant column/input should now be visible in
      - [ ] Customer return edit modal
      - [ ] Inbound shipment edit modal
      - [ ] Stock view detail page
        - [ ] The item variant options on these pages should be available on remote sites after syncing
        - [ ] You should be able to reinitialise remote site and the item variants still populated in e.g. inbound shipment
  - [ ] On OMS Remote site, there is no `Variants` tab in item detail
- #4757 
  - [ ] Using either Android (with camera), or Desktop (with 2d Barcode Scanner)
  - [ ] Open the cold chain equipment section, and click the `Scan` button (this doesn't show on web)
  - [ ] Scan one of the barcodes below
  - [ ] You should be prompted to create a new asset
  - [ ] If you accept, it should show a new asset with the serial number, asset type, and Warenty date populated
  - [ ] The Installation date should default to today
  - [ ] Scanning the same barcode again, should navigate you to the right asset (once it has been created)

2d Matrix examples:

Here's an example raw string you can use to create new QR Code using https://barcode.tec-it.com/en/DataMatrix

Ensure you are using GH light mode, dark mode seems to result in errors!

`(01)00012345600012(11)241007(21)S12345678(241)E003/002(3121)82(3131)67(3111)63(8013)HBD 116(90)001(91)241007-310101(92){"pqs":"https://apps.who.int/immunization_standards/vaccine_quality/pqs_catalogue/LinkPDF.aspx?UniqueID=3bf9439f-3316-49b4-845e-d50360f8280f&TipoDoc=DataSheet&ID=0”}`

PQS Asset Type: E003/002
Serial Number: S1
![barcode (1)](https://github.com/user-attachments/assets/2e9e2a9a-fe98-4da1-ad97-ec8e7fdd1025)

PQS Asset Type: E003/002
Serial Number: S2
![barcode (2)](https://github.com/user-attachments/assets/455f6d7c-8715-4927-b978-4fcb1a10bfda)

PQS Asset Type: E004/055
Serial Number S1
![barcode (4)](https://github.com/user-attachments/assets/4ca5259c-738a-4343-82db-d0a2b1344f3c)

- Miscellaneous changes
  - [ ] On OMS Central server, under Settings > Configuration, enable GAPS store properties (NOTE: this is only available on fresh databases, if it's been run before it can't be run again)
    - [ ] This should enable the `Edit` button in the footer next to the store name, on both central server and remote sites, and clicking it should open the modal with properties populated
    - [ ] There is a `Stock safety buffer` field in the properties
      - [ ] You can edit this on OMS Central
      - [ ] You cannot edit on remote site, but you can see the value synced from central
    - [ ] There is a `Packaging level` field in the properties
      - [ ] You can edit this on OMS Central, and on remote sites
      - [ ] Changes sync in both directions
  - [ ] Equipment detail view -> Details tab, all assets now have a `lifespan` property
    - [ ] Assets from the catalogue should have a default value of 10 years
    - [ ] Non-catalogue assets, this should be enterable
  - [ ] Equipment header -> Update status - there is now an `Unserviceable` status option

**Comment by marthakeezy** [comment]
Tested in #5397 - moving to Done ✅
