### ISSUE TITLE
Report and Requisition (R&R) forms

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4405]
### Overview

[Spec document](https://docs.google.com/document/d/1wZ4R1Gq2GbqAKfCJ0KDXpMDnqEgBNAOLNnnXzEkcQ4I/edit)

Add the ability for health facilities to report on a customisable set of usage metrics as well as the consumption and stock levels of a pre-defined list of items.

The period of reporting should be configurable. This reporting system replaces an existing, excel based, form and should have a similar look and feel to using excel. Some fields / values are calculated, as in the excel version where some cells are showing the results of formulae. 

When complete, forms are submitted and will be sent to the supplying store and can no longer be edited.

### Tasks
- [x] #4408
  - [x] #4409
  - [x] #4410 
- [x] #4412
- [x] #4411
  - [x] #4414
  - [x] #4415
  - [x] #4416
  - [x] #4417 
- [x] #4457
- [x] #4510
- [x] #4513

Future:
- [ ] #4418 (implement with backdated transactions?)
- [ ] #4421 (these can just happen as a dashboard for now)
- [ ] #4475 (pending decision)
- [ ] The number of months used in the calculation is configurable (what calculation?)
- [ ] R&R forms are filterable

#### list view

![Screenshot 2024-07-15 at 12 16 18 PM](https://github.com/user-attachments/assets/a5e60fff-1b3f-4750-9b6e-fdbd657373b2)

#### detail view

![Screenshot 2024-07-15 at 12 22 49 PM](https://github.com/user-attachments/assets/6c2a9ba7-9f08-445f-80f8-8f0837bf0131)

#### editing

![Screenshot 2024-07-15 at 12 21 05 PM](https://github.com/user-attachments/assets/b2f01d99-2b87-4d44-9bc3-a985b25201bd)

### Tests

SETUP
1. You'll need to enable the `Open mSupply: Uses program module` store pref in mSupply
2. You'll need at least one master list configured to be visible in your store, which is a program master list
3. You'll need at least one period schedule with some periods configured - and the period schedule to the master list under the `Program settings` tab
4. In Open mSupply UI, go to Replenishment > R&R Forms
5.  Ensure there has been some activity for the items in your master list during the period you are creating the R&R form for
  a. Have transactions on the days bordering the start/end of the period to confirm values are captured correctly!
6. Add the [R&R Form report](https://github.com/msupply-foundation/open-msupply-reports/tree/main/clients/East-Timor/r-and-r-form) into mSupply (or upsert into omSupply using the new script)

TEST:
- [ ] There is a list of R&R forms available (this will be empty the first time)
- [ ] It is possible to filter and sort the R&R list view (Sort done, filter TODO)
- [ ] It is possible to export the list as a csv file (TODO)
- [ ] You can create a form. Clicking the create modal opens a modal:
  - [ ] If you only have one program, it should be auto-selected. If you have more than one, nothing is preselected.
  - [ ] Once program is selected
    - [ ] If you only have one schedule for that program, it is auto-selected. If you have more than one, nothing is preselected.
    - [ ] You can select any period in that schedule (but only for periods that are in the past)
  - [ ] Supplier is not pre-selected
- [ ] Click create
- [ ] You are redirected to a detail view, which is an editable table
- [ ] The form is pre-populated with values from Open mSupply: this is for values of Initial Balance, Received, Consumed, Adjustments, days out of stock, expiry (the expiry date of the oldest expiring batch of that item)
- [ ] Adjusted consumption is correctly calculated based on number of days out of stock (e.g. for period of 1 month (30 days) consumption was 20 units, but stock out was 10 days, so adjusted consumption would be 30 units)
- [ ] AMC correctly calculated as average of the adjusted monthly consumption for the last 3 periods
- [ ] Maximum = 2*AMC
- [ ] Requested = maximum - final balance, but you can edit this value
- [ ] You can edit the white cells
  - [ ] You can refresh the page to reset your changes
  - [ ] You can click the `confirm` check box to save you changes to a line
  - [ ] You can't finalise the form until all lines are confirmed
- [ ] Once all lines are confirmed, you can finalise the form
  - [ ] You can no longer edit the form
  - [ ] An Internal Order has been created for the lines that you requested quantities for
  - [ ] The Response Requisition was created in the supplying store
- [ ] It is possible to print the R&R form
- [ ] It is possible to export the R&R form as an excel file
- [ ] Creating further R&R forms... click the create button on the list view
  - [ ] The program/schedule/supplier from the previous form are selected automatically, along with the next period in the schedule
  - [ ] If you didn't finalise the previous form, here is a warning that you need to finalise the previous form
  - [ ] After finalising the previous form, you can create the next one
  - [ ] You can only select the next period in the sequence
  - [ ] You can't select a previous period
  - [ ] After finalising the form for the last period available, you get a message that no more periods are available
- [ ] Also please ensure that you can: 
  - [ ] Create R&R forms for the same period schedule/period across different programs
  - [ ] Create R&R forms for the same period schedule/period and program in another store

### Moneyworks Jobcode 🧰

`DFAT:TDEV`

**Comment by mark-prins** [comment]
Part II has been created in #4922

**Comment by marthakeezy** [comment]
R&R forms have been released and individual issues created for bugs found along the way, so moving this epic to Done ✅
