### ISSUE TITLE
Feature: EIR / Vaccination Card

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#4642]
# Vaccination Card

[Spec document](https://docs.google.com/document/d/1CejT3U8jOkdb-lnGfw5eVacuRtRImoLfHNCSonNQNVU/edit)

#### Create and Maintain Immunisation Programs
- [x] #4652 
- [x] #4653 
- [x]  #4654
- [x]  #4655 
- [x]  #4656 
- [x]  #4657

#### Vaccination Card

- [x]  #4660
- [x] #4661
- [ ]  #4663
  - [x] #4665
  - [x] #4737
  - [ ] Delivered dose modal links to related encounter
  - [ ] Add a progress bar summarising the immunisation schedule
- [ ] Capture adherence against each immunisation schedule
- [ ] Capture patient withdrawal - program withdrawn -> adherence shows this?
- [x] #4675
  - [x] #4793
  - [ ] Highlight the period of the patient's age
  - [ ] Highlight doses the patient is ready to receive in this encounter (in the period(s) that a patient is currently within, if min interval has passed)
  - [ ] Hide past periods, unless a vaccination was missed in that period
  - [x] #4710
    - [x] #4711
    - [x] Batch not required if encounter date is in the past
    - [x] Or if not given, capture reason (refused/out of stock)
  - [x] #4713

#### Encounters changes
- [x] #4712
- [x] #4709
- [x] #4714
- [ ] Delete vaccinations
- [ ]  Delete vaccinations when encounter is deleted
- [ ] When finalising, create next scheduled encounter
- [x] #4796 
- [x] Default encounter date to today
- [ ] When pulling a patient from central, also pull encounter data
  - [ ] Sync encounter data between sites (if a patient is at multiple)
- [x] Link to the created prescription from an encounter
- [x] Capture/show facility on encounter
- [ ] Can create an encounter from another facility

#### Patient Management improvements (if time)
- [ ] New patient creation in one single form
- [ ] Add Enrolment in program to creation form
- [ ] When there is only one program, it should be default selected during enrolment
- [ ] Improve the patient search flow when creating patients
- [ ] Remove patients from a facility (transfer to another facility/they move overseas)
- [ ] Delete a patient (if no transactions)

 
### Moneyworks Jobcode 🧰

[DJIGVCDV]

# Testing

### Setup
- [ ] Configure some vaccine items in mSupply
- [ ] Configure an immunisation program in mSupply
    - Create a master list for the program (Items > Master Lists) (it will need at least one item - add your vaccine items!)
    - Under Program Settings
      - Check `This master list is a program`
      - Check `Immunisation program` 
      - Create a Program tag
    - Then under Special > Stores > your store > Master Lists, make the new master list visible
      - Add the `Open mSupply: Uses program module` & `Open mSupply: Uses vaccine module` store preferences, and ensure store is a dispensary
    - Add JSON schemas to document registry (Toolbar Special tab > Show document registry...)
      - You'll need to download files from [programschemas](https://github.com/msupply-foundation/programschemas) repo (for now you'll need to check out the `immunisation-programs` branch)
      - Create new document for program enrolment
        - e.g. Document type: `SomeImmunisationProgramEnrolment`, category: `PROGRAM_ENROLMENT`, context: `your_new_master_list`, name: `Some Immunisation Program`
        - Data schema: from programschemas repo - `immunisation_program/generated/immunisation_program.json`
        - UI schema: from programschemas repo - `immunisation_program/ui_schemas/immunisation_program_ui_schema.json`
      - Create new document for encounter
        - e.g. Document type: `SomeImmunisationProgramEncounter`, category: `ENCOUNTER`, context: `your_new_master_list`, name: `Some Immunisation Program Encounter`
        - Data schema: from programschemas repo - `immunisation_program/generated/encounter_creation.json`
        - UI schema: from programschemas repo - `immunisation_program/ui_schemas/immunisation_program_encounter_ui_schema.json`
  - Under Admin > Edit Users > Your user > Open mSupply Permissions, 
    - Add view and edit permissions for your program (ensure you are setting perms for the correct store 😁)
    - Allow `Can modify central data`

### Testing steps

- [ ] As a central user, you can add a vaccine course to an immunisation program
  - [ ] You can add doses to this course
  - [ ] Add vaccine items to some courses, and no items to others
- [ ] You can enrol a patient in an immunisation program
- [ ] You can view the vaccination card from the patient detail page
  - [ ] You cannot create vaccination events for new rows from this view
  - [ ] You CAN view/edit existing vaccination events from this view (you will need to have created vaccinations already, within an encounter. See below)
- [ ] You can create an encounter for the patient, under the program
- [ ] Encounter view opens to the vaccination card
- [ ] You can create new vaccinations by clicking on a row
  - [ ] If you select Not Given, you are asked to provide a reason
  - [ ] If you selected Given 
    - [ ] You can enter item/batch information, and a prescription is created when you press save
      - [ ] Except if the dose is from a vaccine course with no items configured, then you see a message saying "no items configured.."
    - [ ] When you reopen the modal for that line, there is a popup at the top with a link to the prescription
  - [ ] You can create new vaccinations for an "other" facility
    - [ ] In this case, if you select "given", you CANNOT select a batch
  - [ ] You can create for a date in the past
    - [ ] In this case, if you select "given", you are asked whether or not to create a stock transaction
    - [ ] If you leave the toggle OFF, NO prescription is created when you press save
  - [ ] You can edit existing vaccinations
    - [ ] You will be asked if you want to update/revert existing transactions 
      - [ ] Given -> not given (if you toggle ON revert transaction) should create customer return
      - [ ] Given (but changing batch) should create customer return for old batch and new prescription
      - [ ] Not given -> given should create prescription
    - [ ] If you leave the toggle off, no invoices should be created!
- [ ] Statuses of each row in the card are correct
- [ ] Suggested date in the card should match the LATTER of
  - Last dose date + min interval (defined one the vaccine course dose)
  - The date at which the patient reaches the min age (defined on the vaccine course dose)

**Comment by adamdewey** [comment]
Yo @lache-melvin - I'm getting a bit confused - an immunization schedule IS an immunizaton program so I'm getting a bit confused by the distinction made here. 

Why do we need a specific preference to enable immunization schedules and to link schedules to programs?

**Comment by lache-melvin** [comment]
@adamdewey hehe this is definitely a draft, so please forgive 😁 

There is some level of distinction in that we created immunisation programs for GAPS, but they don't currently link in with patient programs. So in the absence of better naming, the plan is to:

- Change immunisation programs in OMS central (the stuff from GAPS) to be immunisation schedule configuration
- Configure a base patient program for each immunisation program (so we sync through legacy mSupply, and get all the existing patient program functionality)
- In OMS, link that program to the immunisation schedule configuration - then when patients enrol in this program, we can create the vaccine card based on the immunisation schedule configuration

...does that make sense?

**Comment by adamdewey** [comment]
Thanks @lache-melvin !

So I think first thing to clarify is that mine and @richardmoizeau's vision behind the Programs section in Open mSupply wasn't to be just for immunizations, it was to serve as a focal point for top-level users to manage all things program-related at the top level. 

I.e. it would ultimately serve as the go-to place for top-level users who wanted to configure global system settings for HIV, TB, immunization programs etc (also thinking forward to when OG is dropped).

For the rest: 

> Change immunisation programs in OMS central (the stuff from GAPS) to be immunisation schedule configuration

I'm not sure I understand this - does this mean re-naming everything to remove the word 'Program'?  I don't think we should do that..

> Configure a base patient program for each immunisation program (so we sync through legacy mSupply, and get all the existing patient program functionality)

Can this be done on the back-end without exposing to the user that there are 'two kinds' of program?

> In OMS, link that program to the immunisation schedule configuration - then when patients enrol in this program, we can create the vaccine card based on the immunisation schedule configuration

I think we should link in the backend but not make the distinction to the user - it would be better for them to think that programs and schedules are the same thing in the UI. 

Ideally they would just put the word 'Schedule' into the name of their immunization program

**Comment by lache-melvin** [comment]
Caught up in person.. to summarise:

- Immunisation programs need to be patient programs, so they need to be first configured through mSupply
- Then in omSupply, the `Programs > Immunizations` screen is where we would mark these programs as Immunization Programs, and add the additional configuration (the vaccine courses etc.)

So not renaming, just moving from omSupply _creating_ immunisation programs, to it configuring a previously created patient program to be an Immunisation Program.

**Comment by regotaina** [comment]
# Testing 

OMS version: V2.3
mSupply version: V7.17
Platform: Desktop app

### Setup
- [ ] Clone [programschemas](https://github.com/msupply-foundation/programschemas) repo (for now you'll need to check out the `immunisation-programs` branch) and from the repo root, run `./build_all_immunisation_program.sh`
- [ ] Configure some vaccine items in mSupply
- [ ] Configure an immunisation program in mSupply
    - Create a master list for the program (Items > Master Lists) (it will need at least one item - add your vaccine items!)
    - Under Program Settings
      - Check `This master list is a program`
      - Check `Immunisation program` 
      - Create a Program tag
    - Then under Special > Stores > your store > Master Lists, make the new master list visible
      - Add the `Open mSupply: Uses program module` & `Open mSupply: Uses vaccine module` store preferences, and ensure store is a dispensary
    - Add JSON schemas to document registry (Toolbar Special tab > Show document registry...)
      - Create new document for program enrolment
        - e.g. Document type: `SomeImmunisationProgramEnrolment`, category: `PROGRAM_ENROLMENT`, context: `your_new_master_list`, name: `Some Immunisation Program`
        - Data schema: from programschemas repo - `generated/immunisation_program/immunisation_program.json`
        - UI schema: from programschemas repo - `immunisation_program/ui_schemas/immunisation_program_ui_schema.json`
      - Create new document for encounter
        - e.g. Document type: `SomeImmunisationProgramEncounter`, category: `ENCOUNTER`, context: `your_new_master_list`, name: `Some Immunisation Program Encounter`
        - Data schema: from programschemas repo - `generated/immunisation_program/encounter_creation.json`
        - UI schema: from programschemas repo - `immunisation_program/ui_schemas/immunisation_program_encounter_ui_schema.json`
  - Under Admin > Edit Users > Your user > Open mSupply Permissions, 
    - Add view and edit permissions for your program (ensure you are setting perms for the correct store 😁)
    - Allow `Can modify central data`

### Testing steps

- [ ] As a central user, you can add a vaccine course to an immunisation program
  - [ ] You can add doses to this course
  - [ ] Add vaccine items to some courses, and no items to others
- [ ] You can enrol a patient in an immunisation program
- [ ] You can view the vaccination card from the patient detail page
  - [ ] You cannot create vaccination events for new rows from this view
  - [ ] You CAN view/edit existing vaccination events from this view (you will need to have created vaccinations already, within an encounter. See below)
- [ ] You can create an encounter for the patient, under the program
- [ ] Encounter view opens to the vaccination card
- [ ] You can create new vaccinations by clicking on a row
  - [ ] If you select Not Given, you are asked to provide a reason
  - [ ] If you selected Given 
    - [ ] You can enter item/batch information, and a prescription is created when you press save
      - [ ] Except if the dose is from a vaccine course with no items configured, then you see a message saying "no items configured.."
    - [ ] When you reopen the modal for that line, there is a popup at the top with a link to the prescription
  - [ ] You can create new vaccinations for an "other" facility
    - [ ] In this case, if you select "given", you CANNOT select a batch
  - [ ] You can create for a date in the past
    - [ ] In this case, if you select "given", you are asked whether or not to create a stock transaction
    - [ ] If you leave the toggle OFF, NO prescription is created when you press save
  - [ ] You can edit existing vaccinations
    - [ ] You will be asked if you want to update/revert existing transactions 
      - [ ] Given -> not given (if you toggle ON revert transaction) should create customer return
      - [ ] Given (but changing batch) should create customer return for old batch and new prescription
      - [ ] Not given -> given should create prescription
    - [ ] If you leave the toggle off, no invoices should be created!
- [ ] Statuses of each row in the card are correct
- [ ] Suggested date in the card should match the LATTER of
  - Last dose date + min interval (defined one the vaccine course dose)
  - The date at which the patient reaches the min age (defined on the vaccine course dose)

**Comment by regotaina** [comment]
Cannot type a Comment/Note or a Facility Name.
Issue logged #4898

**Comment by regotaina** [comment]
# 🧪 Testing

OMS version: V2.3 RC3
mSupply version: V7.17
Platform: android

### Setup
- [x] Clone [programschemas](https://github.com/msupply-foundation/programschemas) repo (for now you'll need to check out the `immunisation-programs` branch) and from the repo root, run `./build_all_immunisation_program.sh`
- [x] Configure some vaccine items in mSupply
- [x] Configure an immunisation program in mSupply
    - Create a master list for the program (Items > Master Lists) (it will need at least one item - add your vaccine items!)
    - Under Program Settings
      - Check `This master list is a program`
      - Check `Immunisation program` 
      - Create a Program tag
    - Then under Special > Stores > your store > Master Lists, make the new master list visible
      - Add the `Open mSupply: Uses program module` & `Open mSupply: Uses vaccine module` store preferences, and ensure store is a dispensary
    - Add JSON schemas to document registry (Toolbar Special tab > Show document registry...)
      - Create new document for program enrolment
        - e.g. Document type: `SomeImmunisationProgramEnrolment`, category: `PROGRAM_ENROLMENT`, context: `your_new_master_list`, name: `Some Immunisation Program`
        - Data schema: from programschemas repo - `generated/immunisation_program/immunisation_program.json`
        - UI schema: from programschemas repo - `immunisation_program/ui_schemas/immunisation_program_ui_schema.json`
      - Create new document for encounter
        - e.g. Document type: `SomeImmunisationProgramEncounter`, category: `ENCOUNTER`, context: `your_new_master_list`, name: `Some Immunisation Program Encounter`
        - Data schema: from programschemas repo - `generated/immunisation_program/encounter_creation.json`
        - UI schema: from programschemas repo - `immunisation_program/ui_schemas/immunisation_program_encounter_ui_schema.json`
  - Under Admin > Edit Users > Your user > Open mSupply Permissions, 
    - Add view and edit permissions for your program (ensure you are setting perms for the correct store 😁)
    - Allow `Can modify central data`

### Testing steps

- [x] As a central user, you can add a vaccine course to an immunisation program
  - [x] You can add doses to this course
  - [x] Add vaccine items to some courses, and no items to others
- [x] You can enrol a patient in an immunisation program
- [x] You can view the vaccination card from the patient detail page
  - [x] You cannot create vaccination events for new rows from this view
  - [x] You CAN view/edit existing vaccination events from this view (you will need to have created vaccinations already, within an encounter. See below)
- [x] You can create an encounter for the patient, under the program
- [x] Encounter view opens to the vaccination card
- [x] You can create new vaccinations by clicking on a row
  - [x] If you select Not Given, you are asked to provide a reason
  - [x] If you selected Given 
    - [x] You can enter item/batch information, and a prescription is created when you press save
      - [x] Except if the dose is from a vaccine course with no items configured, then you see a message saying "no items configured.."
    - [x] When you reopen the modal for that line, there is a popup at the top with a link to the prescription
  - [x] You can create new vaccinations for an "other" facility
    - [x] In this case, if you select "given", you CANNOT select a batch
  - [x] You can create for a date in the past
    - [x] In this case, if you select "given", you are asked whether or not to create a stock transaction
    - [x] If you leave the toggle OFF, NO prescription is created when you press save
  - [x] You can edit existing vaccinations
    - [ ] You will be asked if you want to update/revert existing transactions 
      - [ ] Given -> not given (if you toggle ON revert transaction) should create customer return
      - [ ] Given (but changing batch) should create customer return for old batch and new prescription
      - [x] Not given -> given should create prescription
    - [ ] If you leave the toggle off, no invoices should be created!
- [x] Statuses of each row in the card are correct
- [ ] Suggested date in the card should match the LATTER of
  - Last dose date + min interval (defined one the vaccine course dose)
  - The date at which the patient reaches the min age (defined on the vaccine course dose)

**Comment by regotaina** [comment]
Will wait for RC4 to keep testing the new design.

Passed the test 👍🏾

**Comment by regotaina** [comment]
There are a few things coming on the next RCs, but closing this issue for now

**Comment by lache-melvin** [comment]
Closing this one as Vaccination Card for 2.3 released - another issue can be created for carryover when we pick up future changes!
