### ISSUE TITLE
Reports Phase 3

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#4668]
In order of priority:

* [x] #5064
* [x] https://github.com/msupply-foundation/open-msupply/issues/4701 (pre requisite broken down below)
   * [x] #5057 and functions
   * [x] #5058 
   * [x] https://github.com/msupply-foundation/open-msupply/issues/4702
* [x] Translation 
   * [x] #4951
* [ ] Versioning 
   * [x] #4791
   * [ ] #4795
* [x] #5056
* [ ] UI Changes
   * [ ] #4753
   * [ ] #4754
   * [ ] #4782
* [x] #5007
* [x] Standardise convert_data.js wasm function file #5201
* [ ] Remove cleanNodes redundant function #5203
* [x] #5182 
* [x] #4882 
* [x] #5312 

---- Future works ---
* [ ] OMS config #4794
* [ ] Testing (ties in with versioning)
   * [ ] Also potentially can do this: https://github.com/msupply-foundation/open-msupply/issues/3537)
   * [ ] #4798
* [ ] Ease of deployment 
   * [ ] https://github.com/msupply-foundation/msupply/issues/14465 already doing this in OMS, not sure if we need this issue anymore
* [ ] Permissions #3383
* [ ] Templates - the report header isn't exported to excel, using a template would allow for the same sort of functionality  #3100

untriaged issues:
* [x] Faster report testing #5200 
* [ ] Refactor report function test file structure #5202 
* [ ] Refactor convert data functions to typescript #5204 
* [x] Consolidate bundlers into one bundler #5205
* [x] Move functions out of standard reports json OR cache functions #5207 
* [ ] #5243
* [x] #5244
* [ ] #5257 
* [ ] #5181 
* [ ] #5130 
* [x] #5093 
* [ ] #5125 

Apart from this we would want to add more internal docs about report creation (how to make report compliant with our excel export logic, etc..)

**Comment by andreievg** [comment]
# Versioning, Testing and Easy of Deployment 

## Problem Space

First of all, report are configurable and sync out to sites, and sites can be on different versions of omSupply (updating all sites is not an easy task). Consider this in the context of the following

* Report might have new views or graphql added
* We might decide to change shape of graphql (not likely)
* We can decide to change shape of our sql schema

For deployment

* It's not that easy to update reports, have to do a lot of clicking and easy to miss report updates, this needs to be improved for support

## Solution

Report specifies 'min' omSupply version, the version best matching current omSupply will be used, this means multiple reports with the same name can exist

Reports in report repo can be tested all at once, against previous and current version of omSupply (would require different datafile for different versions and clients). I think matching output is out of scope but making sure that data we use covers all of the variations of report display (all tera code is run). This would require cloning omSupply repo and checking out different versions.

For ease of deployment we would need to generate 'one' file (for client), with all standard and customised reports, and a function in mSupply to upload this file (should we include original code of the logic functions for reference?).

Doing the above might prove to be time consuming, and maybe we need to 'embed' standard report in omSupply binary. However for clients we would still need manual update of customised reports if they need to be updated to a new version

It sounds like we would need static ids for reports to make sure we don't create duplicates ?

If tests fails we need to have a mechanism to request site config update (through support ?)

Would suggest we remove all of the bash scripts and extend report builder or omSupply cli (would consolidate omSupply cil and report builder). Especially since we would need to do some crawling through report repo to find all reports (all standard report or customised standard report for a client)

In case of versioning, we might want to re-use some functionality for a particular report (this would mean folder structure of reports might change)

**Comment by jmbrunskill** [comment]
@andreievg as discussed, I think we could consider moving these versioned reports to open-mSupply Central.

Advantages
1. No mSupply Changes needed
2. Upgrading central server could allow it to automatically update and remote site reports (if they're comptible)
3. Less dependance on Legacy mSupply

Disadvantages
1. Need to build some Central Server UI to manage the upload of customer reports.

**Comment by jmbrunskill** [comment]
I think the general plan for versioning looks good though! I like tying the compatibility to OMS Version.

There is an issue when a change is made that breaks an older version, e.g. removing a field in graphql (similar to loaders one) We can't tag the old version as incompatible and we'll have to be vigilant to upgrade.
I think for standard reports, we should be ok as we'll be testing, but I think there's risk of breaking custom reports unexpectedly. 

I haven't thought of any magic solutions for this, I guess we could try to add a test function to production for all custom reports?

**Comment by mark-prins** [comment]
That all looks great - thanks for the thought gone into the versioning and management of reports, that's super helpful

I agree with @jmbrunskill - would be good to take this opportunity and remove the OG dependency, and shift report admin to oms central server. 

Custom reports are still a little tricky to manage compatibility and versioning; happy to keep that as a manual task. there's low likelihood of it happening and we can isolate a manual test task to specific clients prior to upgrading. It's a little tedious so it's worth investigating later if we can automate the testing of custom reports.

**Comment by andreievg** [comment]
Add header with logo to all standard/general reports and make sure existing standard report (like requisition) works with the logo set on store

**Comment by andreievg** [comment]
Make sure all standard reports and printouts are included in the bundling process (not just general reports)

**Comment by andreievg** [comment]
Also i would like just one CLI at some point (merging report-builder cli into remote-server-cli)

**Comment by roxy-dao** [comment]
Taking off milestone since issues have been done in V2.5. Please put appropriate milestone for the rest of the carryovers (:

**Comment by roxy-dao** [comment]
Closing in favour of tidy up #6294. Please reopen for remaining issues when relevant.

**Comment by marthakeezy** [comment]
Moving to Done for QA as the existing issues have been tested in V2.5.0. If this issue is reopened, can move back for testing purposes :)

✅
