### ISSUE TITLE
Add front end translations to omSupply reports

### ISSUE THREAD

**Issue by fergie-nz** [msupply-foundation/open-msupply#4682]
Add report translations to mSupply

- [x] https://github.com/msupply-foundation/open-msupply/issues/4676
- [x] https://github.com/msupply-foundation/open-msupply/issues/4677
- [x] https://github.com/msupply-foundation/open-msupply/issues/4678
- [x] https://github.com/msupply-foundation/open-msupply/issues/4679
- [x] https://github.com/msupply-foundation/open-msupply/issues/4680
- [x] https://github.com/msupply-foundation/open-msupply/issues/4681
- [x] https://github.com/msupply-foundation/open-msupply/issues/4720
- [x] #4739

Later we can implement similar translations for Health Supply Hub emails

**Comment by roxy-dao** [comment]
All tasks seem complete. Can this be closed? @fergie-nz

**Comment by DhanyaHerath** [comment]
Same question as above but thought I'd just close it :) @fergie-nz

**Comment by marthakeezy** [comment]
Report translations were tested in V2.3.0 Release Testing, so moving this issue to Done ✅
