### ISSUE TITLE
Manual Requisitions

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#5089]
## IN PROGRESS

Manual requisitions refer to the ability to create manual customer requisitions to supply stock to customers on behalf of the customer.

[Specs document](https://docs.google.com/document/d/1dCVVLxgc-lZaHxwFNqfHpJiTGIYs9OH-VeujjTTL-tM)

### To be implemented
- [x] #5081
- [x] #5118
- [x] #5171
- [x] #5119
- [x] #5177
- [x] #5139
- [x] #5088
- [x] #5190
- [x] #5137
- [x] #5162
- [x] #5134
- [x] #5398
- [ ] #5138
- [x] #5242 
- [x] #5388

### Test Instructions
- [ ] Have programs set up for customers with mSupply stores and those without (to test that you can create program requisitions for customers who aren't using mSupply)
- [ ] For non-mSupply customers, go to their information window -> Tag -> Add tag to ensure that they are using the program
- [ ] Sync mSupply to OMS
- [ ] Go to the Requisition page
- [ ] Click `New Requisition` button
- [ ] If you have programs set up, you should see that you have the option to add either a `Program` Requisition or a `General` Requisition (you should be able to create manual Requisitions for customers who are using mSupply and those who aren't. Indicated with the store icon)

#### Program Requisition
- [ ] First try to create a program Requisition: Choose the program, customer name, order type and period
- [ ] You should be redirected to the Requisition detail view page
- [ ] There should be extra columns in the table: Initial SOH, Incoming, Outgoing, Losses, Additions, Available, Short Expiry, Days out of stock, AMC, MOS, and reason.
- [ ] The `Add Item` button should be disabled.
- [ ] You can read the program information by clicking `More`

https://github.com/user-attachments/assets/2a3b5b9a-f3c2-4862-8864-63fff698bd56

- [ ] Click on a requisition line
- [ ] Get redirected to the requisition line edit page

![Screenshot 2024-11-08 at 11 18 49 AM](https://github.com/user-attachments/assets/e097fb73-2bc9-4779-af2d-e0f69c84bf16)

- [ ] The current item you are looking at should `be bold` and have the `>` icon next to it
- [ ] Try to edit some values. Make sure they are saved properly
- [ ] Entering a value in suggested quantity (that is not 0) will enable the green tick icon to appear in front of the item name
![Screenshot 2024-11-08 at 1 22 43 PM](https://github.com/user-attachments/assets/3a449fa9-a937-4b47-b282-53be5101bf6d)
- [ ] Click on the `Chart` icon next to quantity to supply to see stats relating to your store
![Screenshot 2024-11-08 at 11 35 03 AM](https://github.com/user-attachments/assets/dea39ff6-638e-40fd-9a4f-dd6b62cc47e0)
- [ ] Navigate through the items by either clicking: 
   - [ ] Previous (disabled if this is the first item in the list). Should go back to the previous item on the list
   - [ ] Next (disabled if this is the last item in the list). Should go to the next item on the list
   - [ ] Clicking the item on the list itself
- [ ] Click `Close` button. Should redirect back to the requisition detail page.

#### General Requisition
- [ ] For requisitions transferred from Internal Orders: 
   - [ ] Initial stock on hand should change to stock on hand in the line edit page
   - [ ] You can see a bar icon next to the requested quantity which should show the customer's stock information 
![Screenshot 2024-11-08 at 12 30 15 PM](https://github.com/user-attachments/assets/f179b333-3075-4e53-9927-248320e4bcab)
   - [ ] Should only be able to edit suggested quantity (all the other columns should be hidden 
- [ ] Create a general requisition by clicking the `Add Requisition` button and selecting a customer in the `General` tab
- [ ] This should redirect you to the Requisition page with no lines
- [ ] Click add item -> modal will pop up for you to select the item
- [ ] Select item and be redirected to the Requisition line edit page (noted above initial stock on hand should change to stock on hand)
- [ ] Everything else should be the same as program requisition (extra columns should be hidden)
![Screenshot 2024-11-08 at 12 17 36 PM](https://github.com/user-attachments/assets/cc50217b-178c-4f55-a0e8-46e1bfd61ee7)

**Indicators and global preference tests coming soon**

### Moneyworks Jobcode 🧰

OMS:CIMDV

**Comment by roxy-dao** [comment]
Question: Do we populate values based on existing customer data if user creates a manual requisition for existing customer for some emergency reason?

**Comment by mark-prins** [comment]
I don't think that we can - a store wouldn't have a customer's data available unless they were on the same site.

**Comment by alainsussol** [comment]
### Test Instructions
- [ ] Have programs set up for customers with mSupply stores and those without (to test that you can create program requisitions for customers who aren't using mSupply)
- [ ] For non-mSupply customers, go to their information window -> Tag -> Add tag to ensure that they are using the program
- [ ] Sync mSupply to OMS
- [ ] Go to the Requisition page
- [ ] Click `New Requisition` button
- [ ] If you have programs set up, you should see that you have the option to add either a `Program` Requisition or a `General` Requisition (you should be able to create manual Requisitions for customers who are using mSupply and those who aren't. Indicated with the store icon)

#### Program Requisition
- [ ] First try to create a program Requisition: Choose the program, customer name, order type and period
- [ ] You should be redirected to the Requisition detail view page
- [ ] There should be extra columns in the table: Initial SOH, Incoming, Outgoing, Losses, Additions, Available, Short Expiry, Days out of stock, AMC, MOS, and reason.
- [ ] The `Add Item` button should be disabled.
- [ ] You can read the program information by clicking `More`

https://github.com/user-attachments/assets/2a3b5b9a-f3c2-4862-8864-63fff698bd56

- [ ] Click on a requisition line
- [ ] Get redirected to the requisition line edit page

![Screenshot 2024-11-08 at 11 18 49 AM](https://github.com/user-attachments/assets/e097fb73-2bc9-4779-af2d-e0f69c84bf16)

- [ ] The current item you are looking at should `be bold` and have the `>` icon next to it
- [ ] Try to edit some values. Make sure they are saved properly
- [ ] Entering a value in suggested quantity (that is not 0) will enable the green tick icon to appear in front of the item name
![Screenshot 2024-11-08 at 1 22 43 PM](https://github.com/user-attachments/assets/3a449fa9-a937-4b47-b282-53be5101bf6d)
- [ ] Click on the `Chart` icon next to quantity to supply to see stats relating to your store
![Screenshot 2024-11-08 at 11 35 03 AM](https://github.com/user-attachments/assets/dea39ff6-638e-40fd-9a4f-dd6b62cc47e0)
- [ ] Navigate through the items by either clicking: 
   - [ ] Previous (disabled if this is the first item in the list). Should go back to the previous item on the list
   - [ ] Next (disabled if this is the last item in the list). Should go to the next item on the list
   - [ ] Clicking the item on the list itself
- [ ] Click `Close` button. Should redirect back to the requisition detail page.

#### General Requisition
- [ ] For requisitions transferred from Internal Orders: 
   - [ ] Initial stock on hand should change to stock on hand in the line edit page
   - [ ] You can see a bar icon next to the requested quantity which should show the customer's stock information 
![Screenshot 2024-11-08 at 12 30 15 PM](https://github.com/user-attachments/assets/f179b333-3075-4e53-9927-248320e4bcab)
   - [ ] Should only be able to edit suggested quantity (all the other columns should be hidden 
- [ ] Create a general requisition by clicking the `Add Requisition` button and selecting a customer in the `General` tab
- [ ] This should redirect you to the Requisition page with no lines
- [ ] Click add item -> modal will pop up for you to select the item
- [ ] Select item and be redirected to the Requisition line edit page (noted above initial stock on hand should change to stock on hand)
- [ ] Everything else should be the same as program requisition (extra columns should be hidden)
![Screenshot 2024-11-08 at 12 17 36 PM](https://github.com/user-attachments/assets/cc50217b-178c-4f55-a0e8-46e1bfd61ee7)

**Comment by alainsussol** [comment]
#5431 
#5433 
#5448 **Fixed**
#5516 
#5507

**Comment by roxy-dao** [comment]
Closing. Only global pref issue left and it has its own issue

**Comment by roxy-dao** [comment]
## Indicator Tests
#### Note this currently only works for manual requisitions
- [ ] The indicator tab in the Requisition page shouldn't show up if no indicators have been set up for the program
- [ ] In OG, go to `Master List`
- [ ] Click on the program master list and go to the `Program Settings` tab
- [ ] Either: tick that this program is an `HIV program` or add indicators in the `Regimen data` section
- [ ] Sync to OMS
- [ ] In OMS: Go to `Requisitions`
- [ ] Create a new `Requisition`
- [ ] See `indicator` tab is there
- [ ] Click on either the `Regimen` or `HIV` buttons
- [ ] Be redirect to the indicators edit page
- [ ] (Sorry please finish but the functionality should work the same as the edit requisition line page)

**Comment by alainsussol** [comment]
Issues opened
- [ ] #5610 
- [ ] #5634 
- [ ] #5635
- [ ] #5636
