### ISSUE TITLE
Indicators backend

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#5134]
# Gist

Indicators are a defined list of additional information that may need to be provided by a customer when making a program requisition. This is used for reporting on the performance of the program and are recorded while creating a program requisition. Known as `Regimen data` in CDI.

The key data structure is:

```mermaid
erDiagram
  program ||--o{ program_indicator : relation
  program_indicator ||--o{ indicator_row : relation
  program_indicator ||--o{ indicator_column : relation
  indicator_row ||--o{ indicator_value :relation
  indicator_column ||--o{ indicator_value :relation
  customer_requisition }o--o| program : relation
  indicator_value }o--|| customer_store :relation
  indicator_value }o--|| supplier_store :relation
  customer_store ||--o{ customer_requisition :relation
  supplier_store ||--|| supplier_name :relation
  supplier_name ||--o{ customer_requisition :relation
```
(indicator_attribute_row and _col are actually one table with a type field)

This structure can capture a configurable matrix of information for each program indicator

![image](https://github.com/user-attachments/assets/530ba8fb-ecf6-4bbb-ab40-1ee67f096d26)

## Todo

- [x] program_indicator
- [x] indicator_attribute
- [x] indicator_value
- [x] Repo boilerplate (minimal, leave for later issue)
- [x] Service boilerplate (minimal, leave for later issue)
- [x] translators
- [x] sync/change_log code
- [x] #5305 
- [x] #5310 
- [x] #5340 
- [x] #5215 

### program_indicator

| Column     | type   | indexed | Description                                                                          |
| ---------- | ------ | ------- | ------------------------------------------------------------------------------------ |
| ID         | String | [x]     | PK                                                                                   |
| program_ID | String | [x]     | FK                                                                                   |
| code       | String | [ ]     | a short code (Used mainly for some jank in OG which we probably shouldn't replicate) |
| is_active  | Boolean | [ ]     | soft delete                                                                   |

### indicator_row

| Column       | type    | indexed | Description                                                                                          |
| ------------ | ------- | ------- | ---------------------------------------------------------------------------------------------------- |
| ID           | String  | [x]     | PK                                                                                                   |
| indicator_ID | String  | [x]     | FK                                                                                                   |
| description  | String  | [ ]     | "name" in old UI                                                                                     |
| code         | String  | [ ]     | a short code                                                                                         |
| index        | i64     | [ ]     | what position in the table of values. For row order of questions, and column order of answers/values |
| is_required  | Boolean | [ ]     | will prevent the requisition from being finalised unless completed                                   |
| is_active    | Boolean  | [ ]     | soft delete                                                                                          |

### indicator_column

| Column        | type   | indexed | Description                                                                                                                                                        |
| ------------- | ------ | ------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| ID            | String | [x]     | PK                                                                                                                                                                 |
| indicator_ID  | String | [x]     | FK                                                                                                                                                                 |
| header        | String | [ ]     | "name" in old UI                                                                                                                                                   |
| index         | i64    | [ ]     | what position in the table of values. For row order of questions, and column order of answers/values                                                               |
| value_type    | String | [ ]     | enum(f64, String). OG has `string, number, var`. I don't know what var is. It appears to basically be a string anyway. It appears to never be used for columns 🤷‍♂️. |
| default_value | String | [ ]     | prepopulate the column with this value                                                                                                                             |
| is_active     | Boolean | [ ]     | soft delete      

### indicator_value

| Column      | type   | indexed | Description                                                             |
| ----------- | ------ | ------- | ----------------------------------------------------------------------- |
| ID          | String | [x]     | PK                                                                      |
| facility_ID | String | [x]     | FK store.ID of the store that is the customer in the requisition        |
| store_ID    | String | [x]     | FK store.ID again? Of the store that is the supplier in the requisition |
| period_ID   | String | [x]     | FK                                                                      |
| column_ID   | String | [x]     | FK indicator_attribute.ID                                               |
| row_ID      | String | [x]     | FK indicator_attribute.ID                                               |
| value       | String | [ ]     | The actual value. Numbers are coerced from string to number             |

### Moneyworks Jobcode 🧰

OMS:CIMDV

**Comment by roxy-dao** [comment]
All issues done
