### ISSUE TITLE
GEDSI Improvements

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#5487]
# GEDSI Improvements

Press Release: The site caters for a range of users, with support for enhanced accessibility and usability.

[PRD here](https://docs.google.com/document/d/1hCWBcDE9D8hWudF2ZRfXLKvLbuzqhpXkoSijsax7aw4/edit?tab=t.0)

### New help page
- [x] #5598
- [x] #5599
- [x] #5600
- [ ] #164 (to be broken out further)

### Feedback form
- [x] #5601
- [x] #5602
- [x] #5603
- [x] #5604
- [x] #5605
- [x] #5690
- [x] #5737
- [x] #5823
- [x] #5821
- [ ] Email confirmation of receipt to user - after received by support (?)
- [x] #5805
- [X] #5911

### Usability improvements
- [ ] Add high contrast option to Display Settings
- [ ] Add font size adjustment to Display Settings
- [ ] Adjust font size and contrast from App Footer
- [ ] Accomodate font size changes - this may need to be done incrementally
- [x] #5655
- [x] #5806
- [ ] Show column management menu on column header click
- [x] #5738
- [x] #5739
- [ ] Change more button to a side panel button (needs design)
- [ ] Update app drawer icons
- [ ] Update app drawer order

### New help page
- [ ] On the left menu, a new button called Help is located below the Settings button
- [ ] Clicking on the Help button take you the Help page. URL must be address:port\Help
- [ ] go to another page and press h key. Should take you back to the help page.
- [ ] Command + k (CTRL-K on Windows) and test that searching for help brings up the help page as a result
- [ ] In the help page, you should see 
   - [ ] a section Contact us (see section Feedback form for testing)
   - [ ]  a section User guide
     - [ ] Clicking on the User guide should open your browser and take you the omSupply user guide (https://docs.muspply.foundation/introduction/introduction).

### Settings
- [ ] From the Menu click on the Settings button
- [ ] Controlled by the Access server permission in mSupply OG
![image](https://github.com/user-attachments/assets/6da7c241-c40e-4ee8-b12d-edf7e6a8fcfd) 
   - [ ] if you have not the Access server administration permission enabled then you should only see the Display settings section with only the language option visible (see below) :
![image](https://github.com/user-attachments/assets/5f790c63-23db-42f3-98d4-94c8a795e358)
  - [ ]  if you have the Access server administration permission enabled then you should see all the Settings options (see Below)
![image](https://github.com/user-attachments/assets/2834769e-5f39-4eb0-890f-6c704ccc0991)

      

#### Setup

- [ ] OMS Central MUST be running on desktop - email sending not supported on Android
- [ ] Install MailHog: https://kinsta.com/blog/mailhog/
- [ ] Then, start MailHog by running mailhog in the command line.
- [ ] Plus these settings in your local.yaml configuration file

```yaml
mail:
  host: "localhost"
  port: "1025"
  starttls: false
  username: ""
  password: ""
  from: "no-reply@msupply.foundation"
  interval: 10
```
#### Testing 

![image](https://github.com/user-attachments/assets/1d9a7510-d005-42e5-8a98-b5efb1427d6a)

- [ ] From remote site
- [ ] Go to help page, see contact us form
- [ ] On data entry the send Button is disabled if
  - [ ] The email address is empty
  - [ ] The email address is not valid
  - [ ] The body is empty  
  - [ ] The Request option has not be chosen
  - [ ] otherwise the send button is enabled
- [ ] Click send - fields are cleared, success snack pops up
- [ ] Sync to OMS central
- [ ] Run a manual sync on OMS central
- [ ] Wait up to 10 seconds (or whatever interval you put in local.yaml)
- [ ] Check MailHog (http://localhost:8025/) - you should have received an email with the contents of your contact form
- [ ] Test for both feedback and support request - ensure email mentions the correct contact type

#### Action buttons instead of Actions dropdown list 

Full sweep of the app, anywhere that there is a table

- [ ] If it's a table where line selection is possible, select checkbox column is now on the left hand side
- [ ] Actions dropdown is no longer in the toolbar
- [ ] Selecting the checkboxes replaces the footer with a new actions footer
- [ ] The buttons in the actions footer still behave the same

#### Move Logout button to  footer user
- [ ] There is no Logout button in the Left side Menu
- [ ]  Click on the user name located in the footer
   - [ ]  A popup is displayed
      - [ ] A closing "X" icon is displayed on the top right of the popup
      - [ ] The heading is the user's name
      - [ ]  User's username and email  are displayed in the body of the popup
      - [ ]  Logout button is displayed at the bottom of the popup
   - [ ] Clicking away doesn't close the popup
   - [ ] Clicking the 'X' close the popup
   - [ ] Clicking the logout button logs out the user
   
 
### Moneyworks Jobcode 🧰

OMS:GEDSI

**Comment by roxy-dao** [comment]
#745 😉

**Comment by mariyamsupply** [comment]
About font-size increase:
I imagine by increasing the font size we need to increase all the margins and spacing around. What about adding a scaling to pages instead?
It might be easier to find for users as well (especially if the sticky footer covers the normal footer)
It would sit next to column management (and potentially filters (would need to confirm that))


<img width="1024" alt="Frame 322" src="https://github.com/user-attachments/assets/e39d6151-5674-451c-9468-dd14a4ca05f8" />
<img width="1024" alt="Frame 323" src="https://github.com/user-attachments/assets/18102c5d-fe20-4f3c-bb60-e8edca84d4c5" />
<img width="1024" alt="Frame 324" src="https://github.com/user-attachments/assets/64789578-0bfc-4173-aeca-f5802835820e" />

**Comment by noel-yeldos** [comment]
@lache-melvin based on comments from @marthakeezy, @npendergrast and @andreievg we'll need to manually add a version compatibility check to the feedback form sync. I've added it in the issue description.

From @marthakeezy:
"My remote site is on a higher version than my central OMS server (v2.5.0-reports2 vs. V2.4.3), and while this is expected to work, for the feedback form the remote site creates 2 new tables that are not added to the central server."

**Comment by lache-melvin** [comment]
Closing this one as complete now that 2.5 is in RC phase, offline docs will be in future release 🔥

**Comment by marthakeezy** [comment]
Release testing is tracked in #5884 so moving this issue to Done in the QA board :)
