### ISSUE TITLE
JSON Forms prescriptions -- handle categories

### ISSUE THREAD

**Issue by CarlosNZ** [msupply-foundation/open-msupply#5560]
Changes required:
- Add option to "Prescription" component to specify the `itemCategoryPath`, i.e. where in the JSON data to find the category name
- Add filter functionality to "Items" endpoint to filter by category name
- Update "Prescription" component to retrieve `itemCategoryPath` and pass through to Item Selector ("StockItemSearchInput")
- Update "StockItemSearchInput" to take additional "category" prop to pass to above filter

**Comment by marthakeezy** [comment]
# 🧪 Testing



`V2.4.1-RC3`

- [ ] Re-import/update the UI schema for "Reproductive Health Encounter" as outlined in #5551 
- [ ] Create prescriptions as before (#5551), but note the category restriction on Contraceptive Method -- the Prescription component won't show until a "Prescribed Method" is selected
- [ ] Switching the "Prescribed Method" selection resets the Prescription component (no item selected or lines displayed)
- [ ] Closing the modal and re-opening should persist all the selections
- [ ] Prescription creation works as before, and no other regressions from #5551
