### ISSUE TITLE
🌱 V2.5.0 Release Testing

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5679]
# V2.5.0 Release Testing 🌱

> [!NOTE]
> **Test Scripts** are available [here](https://github.com/msupply-foundation/open-msupply/wiki/Test-scripts), they are updated as the new features are coming out ✍🏼

> [!NOTE]
> Please follow [this document](https://docs.google.com/document/d/1aLQ7QwohBhr53U4jmXnYG0FrBqFDQPxPkO45-YFiLvQ/edit) for the most up-to-date QA practices :)

## v2.5.0 NEW FEATURES
- [x] #5884 
- [x] #5884 Dev Test - @CarlosNZ 
- [x] #5981
- [x] #5981 Dev Test - @lache-melvin 
- [x] #5931
- [x] #5931 Dev Test - @roxy-dao 
- [x] #5885 
- [x] #5885 Dev Test - @jmbrunskill 
    
## WORKFLOWS
These can be either one-store or multiple-store setup; depending on the workflow. 
Priority is to make sure the stock movement is functioning 

### STOCK MOVEMENT WORKFLOWS 
Dev Test - @noel-yeldos ✅ (only #6029)
- [x] #6029
- [x] #6076
- [x] #6115
- [x] #6126
- [x] #6136 
- [x] #6141

### NORMAL ORDERING WORKFLOWS
Dev Test - @zachariah-at-msupply ✅
- [x] #6105
- [x] #6106
- [x] #6183
- [x] #6184

### SYNCHRONISATION: CENTRAL DATA SYNC & SYNC INTEGRATION
Dev Test - @Chris-Petty [#6135 ✅ ]
- [x] #6173 

## GENERAL MODULES
These can be tested in a single-store environment since they're more focused on UI 
Priority is to check/test if no buttons/modules are broken

### DISTRIBUTION
- [x] #6169
- [x] #6206
- [ ] Inbound Returns
- [ ] Customers

### REPLENISHMENT
- [ ] Inbound Shipments
- [ ] Internal Orders
- [ ] Outbound Returns
- [ ] Suppliers

### CATALOGUE
- [ ] Assets
- [ ] Items
- [ ] Master Lists

### INVENTORY
Dev Test - @fergie-nz ✅
- [ ] Locations
- [ ] Stocktakes
- [ ] Stock

### DISPENSARY
- [ ] Patients
- [ ] Prescriptions
- [ ] Encounters

### SETTINGS
Dev Test - @aimee-mcneil-melville ✅
- [ ] Display settings
- [ ] Sync
- [ ] Support
- [ ] Devices

### SYNCHRONISATION
- [ ] Installation
- [ ] Initialisation
- [ ] Synchronisation
- [ ] Reinitialisations
- [ ] Version-updates

### COLD CHAIN
- [ ] Monitoring
- [ ] Sensors
- [ ] Equipment

### MANAGE IMMUNIZATIONS 
- [ ] Configuration
- [ ] Facilities
- [ ] Demographics

### IMMUNIZATIONS PROGRAMS
Dev Test - @GeronimoJohn ✅
- [ ] Immunizations Programs

### PATIENT PROGRAMS
Dev Test - @andreievg ✅
- [ ] Patient Registration
- [ ] Patient List
- [ ] Patient Details View
- [ ] Patient Program Enrolment
- [ ] Patient Program Encounters
- [ ] Viral Load logic
- [ ] Lost to Follow up (LTFU)

### PROGRAM REQUISITIONS
- [ ] Setups
- [ ] Creating a Program Internal Order
- [ ] Program IO Window
- [ ] Requisitions

### REMOTE AUTHORISATION
- [ ] Creating Internal Order
- [ ] Approving Internal Order
- [ ] Supplier Requisition

**Comment by alainsussol** [comment]
## Bug repertoried during release testing

### Dispensing enhancement
- [ ] #5977
- [ ] #5978

### GEDSI

### CIV

### Reports

**Comment by Chris-Petty** [comment]
@alainsussol I wonder if there is an easier way to maintain that list of issues found in testing a release? Perhaps a label? If I open an issue while release testing how do you know how to add it here?

**Comment by alainsussol** [comment]
@Chris-Petty 

> [@alainsussol](https://github.com/alainsussol) I wonder if there is an easier way to maintain that list of issues found in testing a release? Perhaps a label? If I open an issue while release testing how do you know how to add it here?

Thanks for the suggestion and I am sure there is an easier way to do this but it is a journey :). Last Release we had issues listed in multiple Release issues with only a link that I had to click on to see the title of the issue and it's status. When you have 50 links or more in a release issue, it takes a long time to go through them before talking to Roxy on release status. So it was what I came up to try to make my life a bit easier :) . I thought that this way I will have all the bugs found by QA during release testing in one place and it is a bit more readable this way as I can see the issue title, the status and if I hover over the link I can see the severity. A bit more practical than last time. 

In my mind it was to help me to manage issues opened by QA and I didn't have the intention to list issues found during dev testing  or found outside of QA in that list so I didn't think of a way to follow those. But in retrospect, we very probably should list all the bugs found.

I also thought of using a label as it would be easier for everyone to add it but because we need to archive often as we continually reach the project issues limit, I feared to lose some of these labeled issues without realising. But maybe we can use a label in conjunction with an extra column where they are put instead of the done column and reducing the chance that they are archived by mistake ? I am not sure...
 
I agree that it might be easier to proceed differently if we want to list ALL the issues found during the Release testing. I'll try to improve the process for next release. Keep the suggestions/comments coming though, they are very useful :)

**Comment by marthakeezy** [comment]
CLOSING DUE TO V2.5.0 BEING RELEASED (but also will continue regression testing)
